/**
 * Definição completa das 10 Fases Temáticas do JumpBall
 * Cada fase traz desafios visuais, físicas ajustadas, obstáculos e mecânicas próprias.
 */
export const STAGES = [
  {
    id: 1,
    number: 1,
    title: 'Floresta Esmeralda',
    theme: 'forest',
    icon: 'TreePine',
    targetHeight: 1800,
    gravity: 0.32,
    jumpForce: -11.5,
    speedFactor: 1.0,
    wind: 0,
    bgGradient: ['#062419', '#0d402b', '#135c3e'],
    platformColor: '#22c55e',
    platformBorder: '#86efac',
    ballGlow: '#4ade80',
    description: 'Brisa calma e plataformas naturais de carvalho. Perfeita para calibrar o giroscópio e câmera.',
    hazards: [],
    mechanic: 'Plataformas seguras e molas energéticas.'
  },
  {
    id: 2,
    number: 2,
    title: 'Dunas do Saara',
    theme: 'desert',
    icon: 'Sun',
    targetHeight: 2400,
    gravity: 0.33,
    jumpForce: -11.6,
    speedFactor: 1.1,
    wind: 0.15, // Vento suave para a direita
    bgGradient: ['#2e1503', '#542c09', '#7c3f0c'],
    platformColor: '#eab308',
    platformBorder: '#fde047',
    ballGlow: '#facc15',
    description: 'Vento lateral que sopra as dunas. Algumas plataformas de areia desmoronam ao pisar!',
    hazards: ['fragile'],
    mechanic: 'Rajadas de vento suaves e plataformas de areia solta.'
  },
  {
    id: 3,
    number: 3,
    title: 'Abismo Oceânico',
    theme: 'ocean',
    icon: 'Waves',
    targetHeight: 3000,
    gravity: 0.28, // Menor gravidade (efeito de flutuação de água)
    jumpForce: -11.0,
    speedFactor: 1.15,
    wind: 0,
    bgGradient: ['#031726', '#062d47', '#0a4b73'],
    platformColor: '#06b6d4',
    platformBorder: '#67e8f9',
    ballGlow: '#22d3ee',
    description: 'Pressão abissal e alta flutuabilidade. Bolhas gigantes garantem saltos acrobáticos.',
    hazards: ['springs'],
    mechanic: 'Flutuabilidade aquática com saltos prolongados.'
  },
  {
    id: 4,
    number: 4,
    title: 'Cânion Trovejante',
    theme: 'storm',
    icon: 'Zap',
    targetHeight: 3600,
    gravity: 0.35,
    jumpForce: -12.0,
    speedFactor: 1.25,
    wind: -0.2, // Vento oscilante
    bgGradient: ['#140a2b', '#281452', '#411e85'],
    platformColor: '#a855f7',
    platformBorder: '#d8b4fe',
    ballGlow: '#c084fc',
    description: 'Tempestades de raios iluminam o cânion. Plataformas condutoras aceleram a subida.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Plataformas elétricas oscilatórias em alta velocidade.'
  },
  {
    id: 5,
    number: 5,
    title: 'Vulcão Magmático',
    theme: 'volcano',
    icon: 'Flame',
    targetHeight: 4200,
    gravity: 0.38,
    jumpForce: -12.5,
    speedFactor: 1.35,
    wind: 0,
    bgGradient: ['#290606', '#520c0c', '#801414'],
    platformColor: '#ef4444',
    platformBorder: '#fca5a5',
    ballGlow: '#f87171',
    description: 'A lava do núcleo está subindo rapidamente! Não hesite em nenhum salto.',
    hazards: ['lava_rising', 'fragile', 'moving'],
    mechanic: 'Lava incandescente subindo a partir da base.'
  },
  {
    id: 6,
    number: 6,
    title: 'Glaciar Ártico',
    theme: 'arctic',
    icon: 'Snowflake',
    targetHeight: 4800,
    gravity: 0.34,
    jumpForce: -11.8,
    speedFactor: 1.45,
    friction: 0.99, // Baixíssimo atrito (escorregadio)
    wind: 0.25,
    bgGradient: ['#061826', '#0d324f', '#144c77'],
    platformColor: '#38bdf8',
    platformBorder: '#bae6fd',
    ballGlow: '#7dd3fc',
    description: 'Gelo escorregadio e rajadas de nevasca congelante. Mantenha o equilíbrio do celular.',
    hazards: ['ice_slick', 'wind', 'moving'],
    mechanic: 'Superfícies de gelo com inércia contínua.'
  },
  {
    id: 7,
    number: 7,
    title: 'Caverna de Cristais',
    theme: 'crystal',
    icon: 'Gem',
    targetHeight: 5400,
    gravity: 0.32,
    jumpForce: -12.2,
    speedFactor: 1.55,
    wind: 0,
    bgGradient: ['#1f082e', '#3f105e', '#671a99'],
    platformColor: '#ec4899',
    platformBorder: '#fbcfe8',
    ballGlow: '#f472b6',
    description: 'Prismas luminosos refletem feixes energéticos. Portais de dobra espacial entre plataformas.',
    hazards: ['teleport', 'moving', 'springs'],
    mechanic: 'Cristais de ressonância com portais de teletransporte.'
  },
  {
    id: 8,
    number: 8,
    title: 'Santuário Celeste',
    theme: 'sky',
    icon: 'Cloud',
    targetHeight: 6000,
    gravity: 0.29,
    jumpForce: -11.5,
    speedFactor: 1.65,
    wind: -0.15,
    bgGradient: ['#0f172a', '#1e293b', '#334155'],
    platformColor: '#94a3b8',
    platformBorder: '#e2e8f0',
    ballGlow: '#cbd5e1',
    description: 'Acima das nuvens o ar rarefeito exige passos leves em plataformas etéreas.',
    hazards: ['disappearing', 'springs'],
    mechanic: 'Nuvens passageiras que se dissolvem após o salto.'
  },
  {
    id: 9,
    number: 9,
    title: 'Metrópole Cyberpunk',
    theme: 'cyberpunk',
    icon: 'Cpu',
    targetHeight: 7000,
    gravity: 0.39,
    jumpForce: -12.8,
    speedFactor: 1.85,
    wind: 0,
    bgGradient: ['#050814', '#0d1533', '#162354'],
    platformColor: '#00f0ff',
    platformBorder: '#ff0055',
    ballGlow: '#00f0ff',
    description: 'Arranha-céus futuristas com esteiras de alta velocidade e feixes de laser verticais.',
    hazards: ['conveyor', 'lasers', 'moving', 'fragile'],
    mechanic: 'Esteiras rolantes que aceleram a bola lateralmente.'
  },
  {
    id: 10,
    number: 10,
    title: 'Órbita Cósmica Zenith',
    theme: 'cosmos',
    icon: 'Sparkles',
    targetHeight: 8500,
    gravity: 0.25,
    jumpForce: -12.5,
    speedFactor: 2.1,
    wind: 0,
    bgGradient: ['#020208', '#070517', '#110a2e'],
    platformColor: '#8b5cf6',
    platformBorder: '#c4b5fd',
    ballGlow: '#a78bfa',
    description: 'O limiar do universo observável. Microgravidade, campos de atração de matéria escura e velocidade máxima.',
    hazards: ['gravity_well', 'teleport', 'moving', 'lasers'],
    mechanic: 'Poços gravitacionais quânticos e velocidade insana.'
  },
  {
    id: 11,
    number: 11,
    title: 'Cachoeira Ancestral',
    theme: 'waterfall',
    icon: 'Droplets',
    targetHeight: 9500,
    gravity: 0.33,
    jumpForce: -11.8,
    speedFactor: 1.35,
    wind: 0.1,
    bgGradient: ['#042f2e', '#0f766e', '#14b8a6'],
    platformColor: '#2dd4bf',
    platformBorder: '#99f6e4',
    ballGlow: '#5eead4',
    description: 'Cascatas majestosas e bruma refrescante. O fluxo das águas cria correntes e molas que impulsionam os saltos.',
    hazards: ['moving', 'springs'],
    mechanic: 'Correntes de água ascendentes e plataformas rochosas úmidas.'
  },
  {
    id: 12,
    number: 12,
    title: 'Floresta Sagrada Indígena',
    theme: 'indigenous',
    icon: 'Feather',
    targetHeight: 10500,
    gravity: 0.31,
    jumpForce: -12.0,
    speedFactor: 1.45,
    wind: 0,
    bgGradient: ['#1c1917', '#14532d', '#15803d'],
    platformColor: '#84cc16',
    platformBorder: '#d9f99d',
    ballGlow: '#a3e635',
    description: 'Totens ancestrais rúnicos e espíritos da mata protegem a subida sagrada entre copas de árvores milenares.',
    hazards: ['springs', 'fragile', 'moving'],
    mechanic: 'Saltos abençoados pelos espíritos e plataformas rúnicas.'
  },
  {
    id: 13,
    number: 13,
    title: 'Tempestade de Monção',
    theme: 'rain',
    icon: 'CloudRain',
    targetHeight: 11600,
    gravity: 0.35,
    jumpForce: -12.0,
    speedFactor: 1.5,
    wind: -0.25,
    bgGradient: ['#020617', '#0f172a', '#1e293b'],
    platformColor: '#38bdf8',
    platformBorder: '#bae6fd',
    ballGlow: '#7dd3fc',
    description: 'Chuva torrencial contínua e rajadas de vento tempestuoso que desviam a bola com força lateral constante.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Ventos laterais fortes e chuva densa com atrito dinâmico.'
  },
  {
    id: 14,
    number: 14,
    title: 'Tundra Congelada do Inverno',
    theme: 'winter',
    icon: 'Wind',
    targetHeight: 12800,
    gravity: 0.36,
    jumpForce: -12.2,
    speedFactor: 1.55,
    friction: 0.98,
    wind: 0.3,
    bgGradient: ['#082f49', '#0369a1', '#38bdf8'],
    platformColor: '#a5f3fc',
    platformBorder: '#e0f2fe',
    ballGlow: '#67e8f9',
    description: 'Nevasca polar cortante e plataformas cristalinas de gelo eterno com inércia contínua e derrapagem intensa.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Superfícies de gelo com baixíssimo atrito e rajadas de nevasca.'
  },
  {
    id: 15,
    number: 15,
    title: 'Deserto das Tempestades',
    theme: 'dune_storm',
    icon: 'Compass',
    targetHeight: 14000,
    gravity: 0.37,
    jumpForce: -12.4,
    speedFactor: 1.65,
    wind: -0.35,
    bgGradient: ['#451a03', '#78350f', '#b45309'],
    platformColor: '#f59e0b',
    platformBorder: '#fef3c7',
    ballGlow: '#fbbf24',
    description: 'Vórtices de areia ardente e pirâmides no horizonte. As dunas movem-se como esteiras em velocidade voraz.',
    hazards: ['moving', 'fragile', 'conveyor'],
    mechanic: 'Esteiras de areia movediça e rajadas de areia giratórias.'
  },
  {
    id: 16,
    number: 16,
    title: 'Cidadela Flutuante dos Céus',
    theme: 'ruins',
    icon: 'Landmark',
    targetHeight: 15200,
    gravity: 0.28,
    jumpForce: -11.6,
    speedFactor: 1.7,
    wind: 0,
    bgGradient: ['#172554', '#1e1b4b', '#312e81'],
    platformColor: '#818cf8',
    platformBorder: '#e0e7ff',
    ballGlow: '#a5b4fc',
    description: 'Templos e colunas místicas levitando na estratosfera. Fragmentos antigravitacionais geram saltos flutuantes.',
    hazards: ['moving', 'springs', 'fragile'],
    mechanic: 'Gravidade lunar leve com plataformas flutuantes mágicas.'
  },
  {
    id: 17,
    number: 17,
    title: 'Fenda Vulcânica de Obsidiana',
    theme: 'obsidian',
    icon: 'Flame',
    targetHeight: 16500,
    gravity: 0.40,
    jumpForce: -13.0,
    speedFactor: 1.8,
    wind: 0,
    bgGradient: ['#180303', '#3b0707', '#600a0a'],
    platformColor: '#dc2626',
    platformBorder: '#fca5a5',
    ballGlow: '#ef4444',
    description: 'O abismo tectônico mais profundo e perigoso. Rochas de obsidiana incandescentes deslizam sobre rios de magma vivo.',
    hazards: ['moving', 'conveyor', 'fragile'],
    mechanic: 'Esteiras de rocha vulcânica e gravidade extrema.'
  },
  {
    id: 18,
    number: 18,
    title: 'Tempestade Solar Corona',
    theme: 'solar',
    icon: 'SunMedium',
    targetHeight: 17800,
    gravity: 0.32,
    jumpForce: -12.6,
    speedFactor: 1.9,
    wind: 0.4,
    bgGradient: ['#450a0a', '#7c2d12', '#c2410c'],
    platformColor: '#fb923c',
    platformBorder: '#ffedd5',
    ballGlow: '#f97316',
    description: 'Na coroa incandescente de uma estrela colossal. Proeminências de plasma e ventos solares de milhões de graus.',
    hazards: ['moving', 'fragile', 'springs'],
    mechanic: 'Ventos solares de plasma que empurram em direção ao vácuo.'
  },
  {
    id: 19,
    number: 19,
    title: 'Cinturão de Asteroides',
    theme: 'asteroid',
    icon: 'Orbit',
    targetHeight: 19000,
    gravity: 0.27,
    jumpForce: -12.4,
    speedFactor: 2.0,
    wind: 0,
    bgGradient: ['#0f051d', '#1e0b36', '#3b0764'],
    platformColor: '#c084fc',
    platformBorder: '#f3e8ff',
    ballGlow: '#d8b4fe',
    description: 'Campos densos de meteoritos em rotação contínua e poeira cósmica violeta. Pise com precisão cirúrgica.',
    hazards: ['moving', 'fragile', 'conveyor'],
    mechanic: 'Fragmentos rochosos errantes e microgravidade do cinturão.'
  },
  {
    id: 20,
    number: 20,
    title: 'Singularidade Cósmica 20.000m',
    theme: 'singularity',
    icon: 'Atom',
    targetHeight: 20000,
    gravity: 0.24,
    jumpForce: -13.0,
    speedFactor: 2.2,
    wind: 0,
    bgGradient: ['#000000', '#090214', '#1f0033'],
    platformColor: '#f43f5e',
    platformBorder: '#ffe4e6',
    ballGlow: '#fb7185',
    description: 'O cume absoluto do universo a 20.000m! O horizonte de eventos de um buraco negro supermassivo distorce a luz e o tempo.',
    hazards: ['moving', 'springs', 'fragile', 'conveyor'],
    mechanic: 'Velocidade e impulsão extremas no limiar da singularidade final.'
  }
];

export const BALL_SKINS = [
  { id: 'neon-cyan', name: 'Esfera Neon', primary: '#06b6d4', glow: '#22d3ee', trail: '#0891b2' },
  { id: 'plasma-pink', name: 'Pulso Plasma', primary: '#f43f5e', glow: '#fb7185', trail: '#e11d48' },
  { id: 'solar-gold', name: 'Sol de Hélio', primary: '#eab308', glow: '#fde047', trail: '#ca8a04' },
  { id: 'matrix-green', name: 'Córtex Matrix', primary: '#22c55e', glow: '#86efac', trail: '#16a34a' },
  { id: 'cosmic-purple', name: 'Nebulosa Roxa', primary: '#a855f7', glow: '#d8b4fe', trail: '#9333ea' },
  { id: 'fireball', name: 'Meteoro Ígneo', primary: '#f97316', glow: '#fdba74', trail: '#ea580c' }
];
