/**
 * Definição completa das 10 Fases Temáticas do JumpBall
 * Cada fase traz desafios visuais, físicas ajustadas, obstáculos e mecânicas próprias.
 */
export const STAGES = [
  {
    id: 1,
    number: 1,
    title: 'Floresta Esmeralda',
    theme: 'forest',
    icon: 'TreePine',
    targetHeight: 1800,
    gravity: 0.32,
    jumpForce: -11.5,
    speedFactor: 1.0,
    wind: 0,
    bgGradient: ['#062419', '#0d402b', '#135c3e'],
    platformColor: '#22c55e',
    platformBorder: '#86efac',
    ballGlow: '#4ade80',
    description: 'Brisa calma e plataformas naturais de carvalho. Perfeita para calibrar o giroscópio e câmera.',
    hazards: [],
    mechanic: 'Plataformas seguras e molas energéticas.'
  },
  {
    id: 2,
    number: 2,
    title: 'Dunas do Saara',
    theme: 'desert',
    icon: 'Sun',
    targetHeight: 2400,
    gravity: 0.33,
    jumpForce: -11.6,
    speedFactor: 1.1,
    wind: 0.15, // Vento suave para a direita
    bgGradient: ['#2e1503', '#542c09', '#7c3f0c'],
    platformColor: '#eab308',
    platformBorder: '#fde047',
    ballGlow: '#facc15',
    description: 'Vento lateral que sopra as dunas. Algumas plataformas de areia desmoronam ao pisar!',
    hazards: ['fragile'],
    mechanic: 'Rajadas de vento suaves e plataformas de areia solta.'
  },
  {
    id: 3,
    number: 3,
    title: 'Abismo Oceânico',
    theme: 'ocean',
    icon: 'Waves',
    targetHeight: 3000,
    gravity: 0.28, // Menor gravidade (efeito de flutuação de água)
    jumpForce: -11.0,
    speedFactor: 1.15,
    wind: 0,
    bgGradient: ['#031726', '#062d47', '#0a4b73'],
    platformColor: '#06b6d4',
    platformBorder: '#67e8f9',
    ballGlow: '#22d3ee',
    description: 'Pressão abissal e alta flutuabilidade. Bolhas gigantes garantem saltos acrobáticos.',
    hazards: ['springs'],
    mechanic: 'Flutuabilidade aquática com saltos prolongados.'
  },
  {
    id: 4,
    number: 4,
    title: 'Cânion Trovejante',
    theme: 'storm',
    icon: 'Zap',
    targetHeight: 3600,
    gravity: 0.35,
    jumpForce: -12.0,
    speedFactor: 1.25,
    wind: -0.2, // Vento oscilante
    bgGradient: ['#140a2b', '#281452', '#411e85'],
    platformColor: '#a855f7',
    platformBorder: '#d8b4fe',
    ballGlow: '#c084fc',
    description: 'Tempestades de raios iluminam o cânion. Plataformas condutoras aceleram a subida.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Plataformas elétricas oscilatórias em alta velocidade.'
  },
  {
    id: 5,
    number: 5,
    title: 'Vulcão Magmático',
    theme: 'volcano',
    icon: 'Flame',
    targetHeight: 4200,
    gravity: 0.38,
    jumpForce: -12.5,
    speedFactor: 1.35,
    wind: 0,
    bgGradient: ['#290606', '#520c0c', '#801414'],
    platformColor: '#ef4444',
    platformBorder: '#fca5a5',
    ballGlow: '#f87171',
    description: 'A lava do núcleo está subindo rapidamente! Não hesite em nenhum salto.',
    hazards: ['lava_rising', 'fragile', 'moving'],
    mechanic: 'Lava incandescente subindo a partir da base.'
  },
  {
    id: 6,
    number: 6,
    title: 'Glaciar Ártico',
    theme: 'arctic',
    icon: 'Snowflake',
    targetHeight: 4800,
    gravity: 0.34,
    jumpForce: -11.8,
    speedFactor: 1.45,
    friction: 0.99, // Baixíssimo atrito (escorregadio)
    wind: 0.25,
    bgGradient: ['#061826', '#0d324f', '#144c77'],
    platformColor: '#38bdf8',
    platformBorder: '#bae6fd',
    ballGlow: '#7dd3fc',
    description: 'Gelo escorregadio e rajadas de nevasca congelante. Mantenha o equilíbrio do celular.',
    hazards: ['ice_slick', 'wind', 'moving'],
    mechanic: 'Superfícies de gelo com inércia contínua.'
  },
  {
    id: 7,
    number: 7,
    title: 'Caverna de Cristais',
    theme: 'crystal',
    icon: 'Gem',
    targetHeight: 5400,
    gravity: 0.32,
    jumpForce: -12.2,
    speedFactor: 1.55,
    wind: 0,
    bgGradient: ['#1f082e', '#3f105e', '#671a99'],
    platformColor: '#ec4899',
    platformBorder: '#fbcfe8',
    ballGlow: '#f472b6',
    description: 'Prismas luminosos refletem feixes energéticos. Portais de dobra espacial entre plataformas.',
    hazards: ['teleport', 'moving', 'springs'],
    mechanic: 'Cristais de ressonância com portais de teletransporte.'
  },
  {
    id: 8,
    number: 8,
    title: 'Santuário Celeste',
    theme: 'sky',
    icon: 'Cloud',
    targetHeight: 6000,
    gravity: 0.29,
    jumpForce: -11.5,
    speedFactor: 1.65,
    wind: -0.15,
    bgGradient: ['#0f172a', '#1e293b', '#334155'],
    platformColor: '#94a3b8',
    platformBorder: '#e2e8f0',
    ballGlow: '#cbd5e1',
    description: 'Acima das nuvens o ar rarefeito exige passos leves em plataformas etéreas.',
    hazards: ['disappearing', 'springs'],
    mechanic: 'Nuvens passageiras que se dissolvem após o salto.'
  },
  {
    id: 9,
    number: 9,
    title: 'Metrópole Cyberpunk',
    theme: 'cyberpunk',
    icon: 'Cpu',
    targetHeight: 7000,
    gravity: 0.39,
    jumpForce: -12.8,
    speedFactor: 1.85,
    wind: 0,
    bgGradient: ['#050814', '#0d1533', '#162354'],
    platformColor: '#00f0ff',
    platformBorder: '#ff0055',
    ballGlow: '#00f0ff',
    description: 'Arranha-céus futuristas com esteiras de alta velocidade e feixes de laser verticais.',
    hazards: ['conveyor', 'lasers', 'moving', 'fragile'],
    mechanic: 'Esteiras rolantes que aceleram a bola lateralmente.'
  },
  {
    id: 10,
    number: 10,
    title: 'Órbita Cósmica Zenith',
    theme: 'cosmos',
    icon: 'Sparkles',
    targetHeight: 8500,
    gravity: 0.25,
    jumpForce: -12.5,
    speedFactor: 2.1,
    wind: 0,
    bgGradient: ['#020208', '#070517', '#110a2e'],
    platformColor: '#8b5cf6',
    platformBorder: '#c4b5fd',
    ballGlow: '#a78bfa',
    description: 'O limiar do universo observável. Microgravidade, campos de atração de matéria escura e velocidade máxima.',
    hazards: ['gravity_well', 'teleport', 'moving', 'lasers'],
    mechanic: 'Poços gravitacionais quânticos e velocidade insana.'
  },
  {
    id: 11,
    number: 11,
    title: 'Cachoeira Ancestral',
    theme: 'waterfall',
    icon: 'Droplets',
    targetHeight: 9500,
    gravity: 0.33,
    jumpForce: -11.8,
    speedFactor: 1.35,
    wind: 0.1,
    bgGradient: ['#042f2e', '#0f766e', '#14b8a6'],
    platformColor: '#2dd4bf',
    platformBorder: '#99f6e4',
    ballGlow: '#5eead4',
    description: 'Cascatas majestosas e bruma refrescante. O fluxo das águas cria correntes e molas que impulsionam os saltos.',
    hazards: ['moving', 'springs'],
    mechanic: 'Correntes de água ascendentes e plataformas rochosas úmidas.'
  },
  {
    id: 12,
    number: 12,
    title: 'Floresta Sagrada Indígena',
    theme: 'indigenous',
    icon: 'Feather',
    targetHeight: 10500,
    gravity: 0.31,
    jumpForce: -12.0,
    speedFactor: 1.45,
    wind: 0,
    bgGradient: ['#1c1917', '#14532d', '#15803d'],
    platformColor: '#84cc16',
    platformBorder: '#d9f99d',
    ballGlow: '#a3e635',
    description: 'Totens ancestrais rúnicos e espíritos da mata protegem a subida sagrada entre copas de árvores milenares.',
    hazards: ['springs', 'fragile', 'moving'],
    mechanic: 'Saltos abençoados pelos espíritos e plataformas rúnicas.'
  },
  {
    id: 13,
    number: 13,
    title: 'Tempestade de Monção',
    theme: 'rain',
    icon: 'CloudRain',
    targetHeight: 11600,
    gravity: 0.35,
    jumpForce: -12.0,
    speedFactor: 1.5,
    wind: -0.25,
    bgGradient: ['#020617', '#0f172a', '#1e293b'],
    platformColor: '#38bdf8',
    platformBorder: '#bae6fd',
    ballGlow: '#7dd3fc',
    description: 'Chuva torrencial contínua e rajadas de vento tempestuoso que desviam a bola com força lateral constante.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Ventos laterais fortes e chuva densa com atrito dinâmico.'
  },
  {
    id: 14,
    number: 14,
    title: 'Tundra Congelada do Inverno',
    theme: 'winter',
    icon: 'Wind',
    targetHeight: 12800,
    gravity: 0.36,
    jumpForce: -12.2,
    speedFactor: 1.55,
    friction: 0.98,
    wind: 0.3,
    bgGradient: ['#082f49', '#0369a1', '#38bdf8'],
    platformColor: '#a5f3fc',
    platformBorder: '#e0f2fe',
    ballGlow: '#67e8f9',
    description: 'Nevasca polar cortante e plataformas cristalinas de gelo eterno com inércia contínua e derrapagem intensa.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Superfícies de gelo com baixíssimo atrito e rajadas de nevasca.'
  },
  {
    id: 15,
    number: 15,
    title: 'Deserto das Tempestades',
    theme: 'dune_storm',
    icon: 'Compass',
    targetHeight: 14000,
    gravity: 0.37,
    jumpForce: -12.4,
    speedFactor: 1.65,
    wind: -0.35,
    bgGradient: ['#451a03', '#78350f', '#b45309'],
    platformColor: '#f59e0b',
    platformBorder: '#fef3c7',
    ballGlow: '#fbbf24',
    description: 'Vórtices de areia ardente e pirâmides no horizonte. As dunas movem-se como esteiras em velocidade voraz.',
    hazards: ['moving', 'fragile', 'conveyor'],
    mechanic: 'Esteiras de areia movediça e rajadas de areia giratórias.'
  },
  {
    id: 16,
    number: 16,
    title: 'Cidadela Flutuante dos Céus',
    theme: 'ruins',
    icon: 'Landmark',
    targetHeight: 15200,
    gravity: 0.28,
    jumpForce: -11.6,
    speedFactor: 1.7,
    wind: 0,
    bgGradient: ['#172554', '#1e1b4b', '#312e81'],
    platformColor: '#818cf8',
    platformBorder: '#e0e7ff',
    ballGlow: '#a5b4fc',
    description: 'Templos e colunas místicas levitando na estratosfera. Fragmentos antigravitacionais geram saltos flutuantes.',
    hazards: ['moving', 'springs', 'fragile'],
    mechanic: 'Gravidade lunar leve com plataformas flutuantes mágicas.'
  },
  {
    id: 17,
    number: 17,
    title: 'Fenda Vulcânica de Obsidiana',
    theme: 'obsidian',
    icon: 'Flame',
    targetHeight: 16500,
    gravity: 0.40,
    jumpForce: -13.0,
    speedFactor: 1.8,
    wind: 0,
    bgGradient: ['#180303', '#3b0707', '#600a0a'],
    platformColor: '#dc2626',
    platformBorder: '#fca5a5',
    ballGlow: '#ef4444',
    description: 'O abismo tectônico mais profundo e perigoso. Rochas de obsidiana incandescentes deslizam sobre rios de magma vivo.',
    hazards: ['moving', 'conveyor', 'fragile'],
    mechanic: 'Esteiras de rocha vulcânica e gravidade extrema.'
  },
  {
    id: 18,
    number: 18,
    title: 'Tempestade Solar Corona',
    theme: 'solar',
    icon: 'SunMedium',
    targetHeight: 17800,
    gravity: 0.32,
    jumpForce: -12.6,
    speedFactor: 1.9,
    wind: 0.4,
    bgGradient: ['#450a0a', '#7c2d12', '#c2410c'],
    platformColor: '#fb923c',
    platformBorder: '#ffedd5',
    ballGlow: '#f97316',
    description: 'Na coroa incandescente de uma estrela colossal. Proeminências de plasma e ventos solares de milhões de graus.',
    hazards: ['moving', 'fragile', 'springs'],
    mechanic: 'Ventos solares de plasma que empurram em direção ao vácuo.'
  },
  {
    id: 19,
    number: 19,
    title: 'Cinturão de Asteroides',
    theme: 'asteroid',
    icon: 'Orbit',
    targetHeight: 19000,
    gravity: 0.27,
    jumpForce: -12.4,
    speedFactor: 2.0,
    wind: 0,
    bgGradient: ['#0f051d', '#1e0b36', '#3b0764'],
    platformColor: '#c084fc',
    platformBorder: '#f3e8ff',
    ballGlow: '#d8b4fe',
    description: 'Campos densos de meteoritos em rotação contínua e poeira cósmica violeta. Pise com precisão cirúrgica.',
    hazards: ['moving', 'fragile', 'conveyor'],
    mechanic: 'Fragmentos rochosos errantes e microgravidade do cinturão.'
  },
  {
    id: 20,
    number: 20,
    title: 'Singularidade Cósmica 20.000m',
    theme: 'singularity',
    icon: 'Atom',
    targetHeight: 20000,
    gravity: 0.24,
    jumpForce: -13.0,
    speedFactor: 2.2,
    wind: 0,
    bgGradient: ['#000000', '#090214', '#1f0033'],
    platformColor: '#f43f5e',
    platformBorder: '#ffe4e6',
    ballGlow: '#fb7185',
    description: 'O cume absoluto do universo a 20.000m! O horizonte de eventos de um buraco negro supermassivo distorce a luz e o tempo.',
    hazards: ['moving', 'springs', 'fragile', 'conveyor'],
    mechanic: 'Velocidade e impulsão extremas no limiar da singularidade final.'
  },
  {
    id: 21,
    number: 21,
    title: 'Monte Olimpo dos Deuses',
    theme: 'olympus',
    icon: 'Crown',
    targetHeight: 21000,
    gravity: 0.29,
    jumpForce: -12.2,
    speedFactor: 1.6,
    wind: 0.05,
    bgGradient: ['#1e1b4b', '#3b0764', '#581c87'],
    platformColor: '#fbbf24',
    platformBorder: '#fef3c7',
    ballGlow: '#fde047',
    description: 'O santuário dos deuses helênicos. Colunas coríntias de mármore dourado suspensas em nuvens etéreas.',
    hazards: ['springs', 'moving'],
    mechanic: 'Plataformas de ouro místico com impulsão divina elevada.'
  },
  {
    id: 22,
    number: 22,
    title: 'Estádio dos Campeões',
    theme: 'soccer',
    icon: 'Trophy',
    targetHeight: 22000,
    gravity: 0.33,
    jumpForce: -12.0,
    speedFactor: 1.65,
    wind: 0,
    bgGradient: ['#022c22', '#064e3b', '#047857'],
    platformColor: '#22c55e',
    platformBorder: '#86efac',
    ballGlow: '#4ade80',
    description: 'Uma arena de futebol monumental sob os holofotes! O gramado sintético perfeito para arrancadas de glória.',
    hazards: ['moving', 'springs'],
    mechanic: 'Efeito de quique perfeito como uma bola de futebol na grande área.'
  },
  {
    id: 23,
    number: 23,
    title: 'Nau dos Mares Tempestuosos',
    theme: 'ship',
    icon: 'Anchor',
    targetHeight: 23000,
    gravity: 0.30,
    jumpForce: -11.8,
    speedFactor: 1.7,
    wind: -0.25,
    bgGradient: ['#0f172a', '#1e293b', '#0369a1'],
    platformColor: '#0ea5e9',
    platformBorder: '#7dd3fc',
    ballGlow: '#38bdf8',
    description: 'No convés e mastros de um galeão lendário navegando por ondas oceânicas bravias e ventos marinhos fortes.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Balanço marítimo com rajadas de vento oceânico.'
  },
  {
    id: 24,
    number: 24,
    title: 'Primavera das Cerejeiras',
    theme: 'spring_season',
    icon: 'Flower2',
    targetHeight: 24000,
    gravity: 0.27,
    jumpForce: -11.5,
    speedFactor: 1.5,
    wind: 0.1,
    bgGradient: ['#4a044e', '#701a75', '#9d174d'],
    platformColor: '#f472b6',
    platformBorder: '#fbcfe8',
    ballGlow: '#f43f5e',
    description: 'Chuva suave de pétalas de sakura cor-de-rosa sob um céu oriental primaveril de serenidade absoluta.',
    hazards: ['springs'],
    mechanic: 'Brisa floral flutuante que desacelera suavemente a queda.'
  },
  {
    id: 25,
    number: 25,
    title: 'Bosque Dourado de Outono',
    theme: 'autumn',
    icon: 'Leaf',
    targetHeight: 25000,
    gravity: 0.31,
    jumpForce: -11.9,
    speedFactor: 1.6,
    wind: -0.15,
    bgGradient: ['#451a03', '#78350f', '#9a3412'],
    platformColor: '#f97316',
    platformBorder: '#ffedd5',
    ballGlow: '#ea580c',
    description: 'Folhas de carvalho e bordo vermelho-âmbar flutuando em redemoinhos dourados de meia-estação.',
    hazards: ['fragile', 'moving'],
    mechanic: 'Plataformas de folhagem outonal que se desfazem sob peso contínuo.'
  },
  {
    id: 26,
    number: 26,
    title: 'Multiverso dos Heróis',
    theme: 'heroes',
    icon: 'Shield',
    targetHeight: 26000,
    gravity: 0.30,
    jumpForce: -12.8,
    speedFactor: 1.8,
    wind: 0,
    bgGradient: ['#1e1b4b', '#1e3a8a', '#991b1b'],
    platformColor: '#ef4444',
    platformBorder: '#93c5fd',
    ballGlow: '#60a5fa',
    description: 'O epicentro das lendas heroicas! Raios de poder cósmico, escudos de vibranium e energia cinética épica.',
    hazards: ['springs', 'conveyor', 'moving'],
    mechanic: 'Super saltos cinematográficos potencializados por energia heroica.'
  },
  {
    id: 27,
    number: 27,
    title: 'Córtex da Placa-Mãe',
    theme: 'computer',
    icon: 'Cpu',
    targetHeight: 27000,
    gravity: 0.32,
    jumpForce: -12.4,
    speedFactor: 1.85,
    wind: 0,
    bgGradient: ['#022c22', '#064e3b', '#0f766e'],
    platformColor: '#10b981',
    platformBorder: '#a7f3d0',
    ballGlow: '#34d399',
    description: 'Caminhe pelas trilhas de cobre impresso, processadores quânticos e barramentos de fibra de alta frequência.',
    hazards: ['conveyor', 'moving'],
    mechanic: 'Esteiras de dados velozes simulando barramentos de clock de alta precisão.'
  },
  {
    id: 28,
    number: 28,
    title: 'Sinfonia das Estrelas',
    theme: 'music',
    icon: 'Music',
    targetHeight: 28000,
    gravity: 0.28,
    jumpForce: -12.0,
    speedFactor: 1.7,
    wind: 0,
    bgGradient: ['#18181b', '#27272a', '#4c1d95'],
    platformColor: '#a855f7',
    platformBorder: '#e9d5ff',
    ballGlow: '#c084fc',
    description: 'Partituras estelares flutuantes, teclas de piano holográficas e acordes musicais ressoando no vácuo.',
    hazards: ['springs', 'fragile'],
    mechanic: 'Plataformas harmônicas com saltos em cadência rítmica.'
  },
  {
    id: 29,
    number: 29,
    title: 'Teia da Ciber-Rede',
    theme: 'internet',
    icon: 'Globe',
    targetHeight: 29000,
    gravity: 0.30,
    jumpForce: -12.2,
    speedFactor: 1.9,
    wind: 0.1,
    bgGradient: ['#020617', '#0f172a', '#0284c7'],
    platformColor: '#06b6d4',
    platformBorder: '#a5f3fc',
    ballGlow: '#22d3ee',
    description: 'A malha de satélites e nós de fibra da rede mundial. Pacotes de dados trafegando na velocidade da luz.',
    hazards: ['moving', 'conveyor'],
    mechanic: 'Roteamento acelerado com conexões que impulsionam lateralmente.'
  },
  {
    id: 30,
    number: 30,
    title: 'Dimensão dos Polígonos',
    theme: 'geometry',
    icon: 'Shapes',
    targetHeight: 30000,
    gravity: 0.31,
    jumpForce: -12.5,
    speedFactor: 1.9,
    wind: 0,
    bgGradient: ['#172554', '#1e1b4b', '#4338ca'],
    platformColor: '#6366f1',
    platformBorder: '#c7d2fe',
    ballGlow: '#818cf8',
    description: 'Mundo euclidiano puro com icosaedros, tetraedros e prismas neon de ângulos impecáveis.',
    hazards: ['moving', 'fragile', 'springs'],
    mechanic: 'Geometria afiada com ressaltos angulares precisos.'
  },
  {
    id: 31,
    number: 31,
    title: 'Cubo Mágico Tridimensional',
    theme: 'magic_cube',
    icon: 'Boxes',
    targetHeight: 31000,
    gravity: 0.29,
    jumpForce: -12.3,
    speedFactor: 1.95,
    wind: 0,
    bgGradient: ['#1e1b4b', '#312e81', '#1e293b'],
    platformColor: '#eab308',
    platformBorder: '#fef08a',
    ballGlow: '#facc15',
    description: 'Um labirinto cósmico de cubos coloridos 3x3x3 que giram e reconfiguram suas faces em tempo real.',
    hazards: ['moving', 'conveyor', 'fragile'],
    mechanic: 'Faces em rotação que alternam cores e propriedades cinéticas.'
  },
  {
    id: 32,
    number: 32,
    title: 'Reino Doce de Confeitos',
    theme: 'candy',
    icon: 'Cookie',
    targetHeight: 32000,
    gravity: 0.28,
    jumpForce: -12.0,
    speedFactor: 1.75,
    wind: 0,
    bgGradient: ['#500724', '#831843', '#be185d'],
    platformColor: '#ec4899',
    platformBorder: '#fbcfe8',
    ballGlow: '#f472b6',
    description: 'Montanhas de marshmallow, bengalas doces de hortelã e nuvens de algodão-doce açucarado.',
    hazards: ['springs', 'fragile'],
    mechanic: 'Gelatina elástica que amortece o pouso e multiplica a propulsão do salto.'
  },
  {
    id: 33,
    number: 33,
    title: 'Covil do Dragão de Fogo',
    theme: 'dragon',
    icon: 'Flame',
    targetHeight: 33000,
    gravity: 0.35,
    jumpForce: -12.7,
    speedFactor: 2.0,
    wind: 0.2,
    bgGradient: ['#450a0a', '#7f1d1d', '#991b1b'],
    platformColor: '#dc2626',
    platformBorder: '#fecaca',
    ballGlow: '#ef4444',
    description: 'Nas profundezas da caverna do dragão ancestral, onde rios de ouro fundido banham estalagmites incandescentes.',
    hazards: ['moving', 'fragile'],
    mechanic: 'Ondas de choque térmico que exigem movimentação rápida sem paradas.'
  },
  {
    id: 34,
    number: 34,
    title: 'Fliperama Pixel 8-Bit',
    theme: 'arcade',
    icon: 'Gamepad2',
    targetHeight: 34000,
    gravity: 0.32,
    jumpForce: -12.4,
    speedFactor: 2.0,
    wind: 0,
    bgGradient: ['#0f051d', '#2e1065', '#581c87'],
    platformColor: '#06b6d4',
    platformBorder: '#67e8f9',
    ballGlow: '#22d3ee',
    description: 'Uma homenagem nostálgica aos arcades clássicos dos anos 80 com gráficos pixelados e sintetizadores chiptune.',
    hazards: ['conveyor', 'springs'],
    mechanic: 'Física retrô acelerada com plataformas arcade vibrantes.'
  },
  {
    id: 35,
    number: 35,
    title: 'Metrópole Flutuante Neon',
    theme: 'metropolis',
    icon: 'Building2',
    targetHeight: 35000,
    gravity: 0.30,
    jumpForce: -12.5,
    speedFactor: 2.05,
    wind: -0.1,
    bgGradient: ['#020617', '#1e1b4b', '#1e3a8a'],
    platformColor: '#38bdf8',
    platformBorder: '#bae6fd',
    ballGlow: '#0ea5e9',
    description: 'Arranha-céus quilométricos com aerotrens magnéticos e passarelas holográficas na estratosfera urbana.',
    hazards: ['moving', 'conveyor', 'fragile'],
    mechanic: 'Plataformas de aerotrem magnético que cruzam a tela em alta velocidade.'
  },
  {
    id: 36,
    number: 36,
    title: 'Véu da Aurora Boreal',
    theme: 'aurora',
    icon: 'Sparkles',
    targetHeight: 36000,
    gravity: 0.26,
    jumpForce: -12.0,
    speedFactor: 1.8,
    wind: 0.15,
    bgGradient: ['#022c22', '#064e3b', '#0369a1'],
    platformColor: '#34d399',
    platformBorder: '#a7f3d0',
    ballGlow: '#2dd4bf',
    description: 'Faixas ondulantes de plasma magnético verde-esmeralda e violeta cortando o céu glacial polar.',
    hazards: ['springs', 'moving'],
    mechanic: 'Ondas geomagnéticas que produzem saltos etéreos prolongados.'
  },
  {
    id: 37,
    number: 37,
    title: 'Parque de Diversões Cósmico',
    theme: 'carnival',
    icon: 'Ticket',
    targetHeight: 37000,
    gravity: 0.31,
    jumpForce: -12.6,
    speedFactor: 2.1,
    wind: 0,
    bgGradient: ['#3b0764', '#701a75', '#a21caf'],
    platformColor: '#f43f5e',
    platformBorder: '#fecdd3',
    ballGlow: '#fb7185',
    description: 'Roda-gigante cósmica, montanha-russa gravitacional e tendas mágicas iluminadas por milhares de lâmpadas neon.',
    hazards: ['moving', 'springs', 'conveyor'],
    mechanic: 'Loopings acrobáticos e plataformas de montanha-russa super velozes.'
  },
  {
    id: 38,
    number: 38,
    title: 'Pirâmides do Egito Ancestral',
    theme: 'pyramids',
    icon: 'Pyramid',
    targetHeight: 38000,
    gravity: 0.34,
    jumpForce: -12.5,
    speedFactor: 2.15,
    wind: 0.2,
    bgGradient: ['#451a03', '#713f12', '#a16207'],
    platformColor: '#eab308',
    platformBorder: '#fef9c3',
    ballGlow: '#ca8a04',
    description: 'Monumentos imortais no deserto dos faraós. Hieróglifos gravados em blocos de calcário dourado sob o Sol de Rá.',
    hazards: ['fragile', 'moving'],
    mechanic: 'Areias do tempo com plataformas ancestrais que requerem ritmo milimétrico.'
  },
  {
    id: 39,
    number: 39,
    title: 'Fábrica Steampunk de Bronze',
    theme: 'steampunk',
    icon: 'Cog',
    targetHeight: 39000,
    gravity: 0.36,
    jumpForce: -13.0,
    speedFactor: 2.2,
    wind: 0,
    bgGradient: ['#292524', '#44403c', '#78350f'],
    platformColor: '#d97706',
    platformBorder: '#fed7aa',
    ballGlow: '#b45309',
    description: 'Caldeiras titânicas, manômetros a vapor, pistões de cobre e engrenagens gigantescas em rotação contínua.',
    hazards: ['moving', 'conveyor', 'fragile'],
    mechanic: 'Válvulas de vapor sob pressão e esteiras de engrenagens industriais.'
  },
  {
    id: 40,
    number: 40,
    title: 'Hiperespaço Quântico Infinito',
    theme: 'quantum',
    icon: 'Infinity',
    targetHeight: 40000,
    gravity: 0.22,
    jumpForce: -13.5,
    speedFactor: 2.4,
    wind: 0,
    bgGradient: ['#000000', '#030712', '#1e1b4b'],
    platformColor: '#38bdf8',
    platformBorder: '#e0e7ff',
    ballGlow: '#818cf8',
    description: 'O limiar supremo a 40.000m! A convergência de todas as realidades através de um túnel de dobra quântica infinita.',
    hazards: ['moving', 'springs', 'fragile', 'conveyor'],
    mechanic: 'Velocidade de dobra cósmica no ápice final de toda a jornada do JumpBall.'
  },
  {
    id: 41,
    number: 41,
    title: 'Pedreira dos Titãs de Rocha',
    theme: 'rock',
    icon: 'Pickaxe',
    targetHeight: 41000,
    gravity: 0.35,
    jumpForce: -12.6,
    speedFactor: 2.1,
    wind: 0,
    bgGradient: ['#1c1917', '#292524', '#44403c'],
    platformColor: '#78716c',
    platformBorder: '#d6d3d1',
    ballGlow: '#a8a29e',
    description: 'Paredões ciclópicos de rocha de granito e ardósia. Blocos monolíticos brutos e pedregulhos instáveis.',
    hazards: ['spikes', 'moving', 'fragile'],
    mechanic: 'Pedras e cascalho que despencam da pedreira e espigões de pedra afiada.'
  },
  {
    id: 42,
    number: 42,
    title: 'Fundição de Ferro e Aço',
    theme: 'iron',
    icon: 'Anvil',
    targetHeight: 42000,
    gravity: 0.37,
    jumpForce: -13.0,
    speedFactor: 2.2,
    wind: 0,
    bgGradient: ['#0f172a', '#1e293b', '#334155'],
    platformColor: '#64748b',
    platformBorder: '#94a3b8',
    ballGlow: '#cbd5e1',
    description: 'Vigas maciças de ferro fundido, correntes titânicas e caldeiras incandescentes forjando aço pesado.',
    hazards: ['spikes', 'conveyor', 'moving'],
    mechanic: 'Barras de ferro e faíscas incandescentes em ambiente metalúrgico denso.'
  },
  {
    id: 43,
    number: 43,
    title: 'Serraria dos Troncos de Madeira',
    theme: 'wood',
    icon: 'Axe',
    targetHeight: 43000,
    gravity: 0.31,
    jumpForce: -12.4,
    speedFactor: 2.0,
    wind: 0.1,
    bgGradient: ['#271708', '#451a03', '#713f12'],
    platformColor: '#92400e',
    platformBorder: '#fde68a',
    ballGlow: '#b45309',
    description: 'Pilhas imensas de toras de madeira de lei, vigas de carvalho maciço e pontes rústicas suspensas.',
    hazards: ['spikes', 'fragile', 'moving'],
    mechanic: 'Troncos pesados despencando e plataformas de madeira com lascas afiadas.'
  }
];

export const BALL_SKINS = [
  { id: 'neon-cyan', name: 'Esfera Neon', primary: '#06b6d4', glow: '#22d3ee', trail: '#0891b2' },
  { id: 'plasma-pink', name: 'Pulso Plasma', primary: '#f43f5e', glow: '#fb7185', trail: '#e11d48' },
  { id: 'solar-gold', name: 'Sol de Hélio', primary: '#eab308', glow: '#fde047', trail: '#ca8a04' },
  { id: 'matrix-green', name: 'Córtex Matrix', primary: '#22c55e', glow: '#86efac', trail: '#16a34a' },
  { id: 'cosmic-purple', name: 'Nebulosa Roxa', primary: '#a855f7', glow: '#d8b4fe', trail: '#9333ea' },
  { id: 'fireball', name: 'Meteoro Ígneo', primary: '#f97316', glow: '#fdba74', trail: '#ea580c' }
];
