-- ==============================================================================
-- JUMPBALL: INSERÇÃO E ATUALIZAÇÃO DAS 150 FASES OFICIAIS DO JOGO
-- ==============================================================================

INSERT INTO public.stages (stage_number, title, theme, description, target_height, gravity, speed_factor, obstacle_types)
VALUES
(1, 'Floresta Esmeralda', 'forest', 'Brisa calma e plataformas naturais de carvalho. Perfeita para calibrar o giroscópio e câmera.', 1800, 0.32, 1, ARRAY[]::TEXT[]),
(2, 'Dunas do Saara', 'desert', 'Vento lateral que sopra as dunas. Algumas plataformas de areia desmoronam ao pisar!', 2400, 0.33, 1.1, ARRAY['fragile']::TEXT[]),
(3, 'Abismo Oceânico', 'ocean', 'Pressão abissal e alta flutuabilidade. Bolhas gigantes garantem saltos acrobáticos.', 3000, 0.28, 1.15, ARRAY['springs']::TEXT[]),
(4, 'Cânion Trovejante', 'storm', 'Tempestades de raios iluminam o cânion. Plataformas condutoras aceleram a subida.', 3600, 0.35, 1.25, ARRAY['moving', 'fragile']::TEXT[]),
(5, '👑 CHEFÃO 1: Silvano, Titã da Mata', 'forest', 'BATALHA DE CHEFÃO! Silvano, o Titã da Floresta, arremessa galhos e vinhas espinhosas. Pule nas baterias energéticas para vencê-lo!', 4200, 0.36, 1.35, ARRAY['fragile', 'moving']::TEXT[]),
(6, 'Glaciar Ártico', 'arctic', 'Gelo escorregadio e rajadas de nevasca congelante. Mantenha o equilíbrio do celular.', 4800, 0.34, 1.45, ARRAY['ice_slick', 'wind', 'moving']::TEXT[]),
(7, 'Caverna de Cristais', 'crystal', 'Prismas luminosos refletem feixes energéticos. Portais de dobra espacial entre plataformas.', 5400, 0.32, 1.55, ARRAY['teleport', 'moving', 'springs']::TEXT[]),
(8, 'Santuário Celeste', 'sky', 'Acima das nuvens o ar rarefeito exige passos leves em plataformas etéreas.', 6000, 0.29, 1.65, ARRAY['disappearing', 'springs']::TEXT[]),
(9, 'Metrópole Cyberpunk', 'cyberpunk', 'Arranha-céus futuristas com esteiras de alta velocidade e feixes de laser verticais.', 7000, 0.39, 1.85, ARRAY['conveyor', 'lasers', 'moving', 'fragile']::TEXT[]),
(10, '👑 CHEFÃO 2: Faraó de Pedra de Rá', 'pyramids', 'BATALHA DE CHEFÃO! O guardião milenar desperta em sua pirâmide cósmica lançando escaravelhos e tempestades de arenito.', 8500, 0.33, 1.8, ARRAY['moving', 'fragile']::TEXT[]),
(11, 'Cachoeira Ancestral', 'waterfall', 'Cascatas majestosas e bruma refrescante. O fluxo das águas cria correntes e molas que impulsionam os saltos.', 9500, 0.33, 1.35, ARRAY['moving', 'springs']::TEXT[]),
(12, 'Floresta Sagrada Indígena', 'indigenous', 'Totens ancestrais rúnicos e espíritos da mata protegem a subida sagrada entre copas de árvores milenares.', 10500, 0.31, 1.45, ARRAY['springs', 'fragile', 'moving']::TEXT[]),
(13, 'Tempestade de Monção', 'rain', 'Chuva torrencial contínua e rajadas de vento tempestuoso que desviam a bola com força lateral constante.', 11600, 0.35, 1.5, ARRAY['moving', 'fragile']::TEXT[]),
(14, 'Tundra Congelada do Inverno', 'winter', 'Nevasca polar cortante e plataformas cristalinas de gelo eterno com inércia contínua e derrapagem intensa.', 12800, 0.36, 1.55, ARRAY['moving', 'fragile']::TEXT[]),
(15, '👑 CHEFÃO 3: Leviatã das Marés', 'ocean', 'BATALHA DE CHEFÃO! A criatura colossal das fossas oceânicas invoca jatos d''água torrenciais e águas-vivas elétricas.', 14000, 0.3, 1.65, ARRAY['moving', 'springs']::TEXT[]),
(16, 'Cidadela Flutuante dos Céus', 'ruins', 'Templos e colunas místicas levitando na estratosfera. Fragmentos antigravitacionais geram saltos flutuantes.', 15200, 0.28, 1.7, ARRAY['moving', 'springs', 'fragile']::TEXT[]),
(17, 'Fenda Vulcânica de Obsidiana', 'obsidian', 'O abismo tectônico mais profundo e perigoso. Rochas de obsidiana incandescentes deslizam sobre rios de magma vivo.', 16500, 0.4, 1.8, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(18, 'Tempestade Solar Corona', 'solar', 'Na coroa incandescente de uma estrela colossal. Proeminências de plasma e ventos solares de milhões de graus.', 17800, 0.32, 1.9, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(19, 'Cinturão de Asteroides', 'asteroid', 'Campos densos de meteoritos em rotação contínua e poeira cósmica violeta. Pise com precisão cirúrgica.', 19000, 0.27, 2, ARRAY['moving', 'fragile', 'conveyor']::TEXT[]),
(20, '👑 CHEFÃO 4: Colosso dos Relâmpagos', 'storm', 'BATALHA DE CHEFÃO! Um titã de alta voltagem descarrega tempestades de raios contínuas no topo do cânion.', 20000, 0.32, 2, ARRAY['moving', 'fragile']::TEXT[]),
(21, 'Monte Olimpo dos Deuses', 'olympus', 'O santuário dos deuses helênicos. Colunas coríntias de mármore dourado suspensas em nuvens etéreas.', 21000, 0.29, 1.6, ARRAY['springs', 'moving']::TEXT[]),
(22, 'Estádio dos Campeões', 'soccer', 'Uma arena de futebol monumental sob os holofotes! O gramado sintético perfeito para arrancadas de glória.', 22000, 0.33, 1.65, ARRAY['moving', 'springs']::TEXT[]),
(23, 'Nau dos Mares Tempestuosos', 'ship', '🏃‍♂️ PERCURSO HORIZONTAL! Corra pelo convés e mastros de um galeão lendário navegando por ondas oceânicas bravias. Não caia no mar!', 23000, 0.36, 1.7, ARRAY['moving', 'fragile']::TEXT[]),
(24, 'Primavera das Cerejeiras', 'spring_season', 'Chuva suave de pétalas de sakura cor-de-rosa sob um céu oriental primaveril de serenidade absoluta.', 24000, 0.27, 1.5, ARRAY['springs']::TEXT[]),
(25, '👑 CHEFÃO 5: Gólem Glacial de Neve', 'arctic', 'BATALHA DE CHEFÃO! O soberano do zero absoluto tenta congelar seus saltos com chuvas de estalactites pontiagudas.', 25000, 0.33, 1.7, ARRAY['moving', 'fragile']::TEXT[]),
(26, 'Multiverso dos Heróis', 'heroes', 'O epicentro das lendas heroicas! Raios de poder cósmico, escudos de vibranium e energia cinética épica.', 26000, 0.3, 1.8, ARRAY['springs', 'conveyor', 'moving']::TEXT[]),
(27, 'Córtex da Placa-Mãe', 'computer', 'Caminhe pelas trilhas de cobre impresso, processadores quânticos e barramentos de fibra de alta frequência.', 27000, 0.32, 1.85, ARRAY['conveyor', 'moving']::TEXT[]),
(28, 'Sinfonia das Estrelas', 'music', 'Partituras estelares flutuantes, teclas de piano holográficas e acordes musicais ressoando no vácuo.', 28000, 0.28, 1.7, ARRAY['springs', 'fragile']::TEXT[]),
(29, 'Teia da Ciber-Rede', 'internet', 'A malha de satélites e nós de fibra da rede mundial. Pacotes de dados trafegando na velocidade da luz.', 29000, 0.3, 1.9, ARRAY['moving', 'conveyor']::TEXT[]),
(30, '👑 CHEFÃO 6: Dragão Solar de Magma', 'volcano', 'BATALHA DE CHEFÃO! A lendária serpente de fogo desperta do coração do vulcão cospindo rochas incandescentes.', 30000, 0.36, 2, ARRAY['lava_rising', 'moving', 'fragile']::TEXT[]),
(31, 'Cubo Mágico Tridimensional', 'magic_cube', 'Um labirinto cósmico de cubos coloridos 3x3x3 que giram e reconfiguram suas faces em tempo real.', 31000, 0.29, 1.95, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(32, 'Reino Doce de Confeitos', 'candy', 'Montanhas de marshmallow, bengalas doces de hortelã e nuvens de algodão-doce açucarado.', 32000, 0.28, 1.75, ARRAY['springs', 'fragile']::TEXT[]),
(33, 'Covil do Dragão de Fogo', 'dragon', 'Nas profundezas da caverna do dragão ancestral, onde rios de ouro fundido banham estalagmites incandescentes.', 33000, 0.35, 2, ARRAY['moving', 'fragile']::TEXT[]),
(34, 'Fliperama Pixel 8-Bit', 'arcade', 'Uma homenagem nostálgica aos arcades clássicos dos anos 80 com gráficos pixelados e sintetizadores chiptune.', 34000, 0.32, 2, ARRAY['conveyor', 'springs']::TEXT[]),
(35, '👑 CHEFÃO 7: Overlord IA Matrix', 'cyberpunk', 'BATALHA DE CHEFÃO! A inteligência artificial suprema da metrópole aciona esteiras aceleradoras e feixes de laser verticais.', 35000, 0.34, 2.1, ARRAY['conveyor', 'moving', 'fragile']::TEXT[]),
(36, 'Véu da Aurora Boreal', 'aurora', 'Faixas ondulantes de plasma magnético verde-esmeralda e violeta cortando o céu glacial polar.', 36000, 0.26, 1.8, ARRAY['springs', 'moving']::TEXT[]),
(37, 'Parque de Diversões Cósmico', 'carnival', 'Roda-gigante cósmica, montanha-russa gravitacional e tendas mágicas iluminadas por milhares de lâmpadas neon.', 37000, 0.31, 2.1, ARRAY['moving', 'springs', 'conveyor']::TEXT[]),
(38, 'Pirâmides do Egito Ancestral', 'pyramids', 'Monumentos imortais no deserto dos faraós. Hieróglifos gravados em blocos de calcário dourado sob o Sol de Rá.', 38000, 0.34, 2.15, ARRAY['fragile', 'moving']::TEXT[]),
(39, 'Fábrica Steampunk de Bronze', 'steampunk', '🏃‍♂️ PERCURSO HORIZONTAL! Atravesse a fábrica steampunk repleta de caldeiras, pistões de cobre e engrenagens colossais girando!', 39000, 0.38, 2.2, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(40, '👑 CHEFÃO 8: Singularidade Multiversal', 'quantum', 'BATALHA DE CHEFÃO MULTIVERSAL! A Singularidade abre fendas no contínuo espaço-tempo e ENVIA O JOGADOR PARA UM UNIVERSO PARALELO!', 40000, 0.26, 2.3, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(41, 'Pedreira dos Titãs de Rocha', 'rock', 'Paredões ciclópicos de rocha de granito e ardósia. Blocos monolíticos brutos e pedregulhos instáveis.', 41000, 0.35, 2.1, ARRAY['spikes', 'moving', 'fragile']::TEXT[]),
(42, 'Fundição de Ferro e Aço', 'iron', 'Vigas maciças de ferro fundido, correntes titânicas e caldeiras incandescentes forjando aço pesado.', 42000, 0.37, 2.2, ARRAY['spikes', 'conveyor', 'moving']::TEXT[]),
(43, 'Serraria dos Troncos de Madeira', 'wood', 'Pilhas imensas de toras de madeira de lei, vigas de carvalho maciço e pontes rústicas suspensas.', 43000, 0.31, 2, ARRAY['spikes', 'fragile', 'moving']::TEXT[]),
(44, 'Coliseu dos Heróis de Aço', 'heroes', 'A arena dos maiores campeões da galáxia! Estandartes heróicos, símbolos titânicos e desafios de pura bravura.', 44000, 0.33, 2.1, ARRAY['moving', 'springs', 'conveyor']::TEXT[]),
(45, '👑 CHEFÃO 9: Autômato Titânico de Bronze', 'steampunk', 'BATALHA DE CHEFÃO! A máquina industrial suprema de bronze gira engrenagens ciclópicas e solta vapor superaquecido.', 45000, 0.35, 2.2, ARRAY['moving', 'fragile', 'conveyor']::TEXT[]),
(46, 'Singularidade do Vazio Cósmico', 'singularity', 'O horizonte de eventos de um buraco negro supermassivo. Distorções ópticas gravitacionais atraindo tudo ao centro.', 46000, 0.38, 2.3, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(47, 'Muralha do Arcade Retrô', 'arcade', 'Um labirinto nostálgico pixelado com telas CRT, efeitos glitch e plataformas que parecem saídas de clássicos dos anos 80.', 47000, 0.3, 2.35, ARRAY['springs', 'moving', 'conveyor']::TEXT[]),
(48, 'Santuário de Aurora Boreal', 'aurora', 'Cortinas etéreas de luz esmeralda e turquesa ondulando nos confins da estratosfera orbital.', 48000, 0.29, 2.2, ARRAY['fragile', 'springs', 'moving']::TEXT[]),
(49, 'Vórtice do Tempo Infinito', 'cosmos', 'A penúltima fronteira! Linhas temporais se cruzando em constelações brilhantes rumo à marca de 50.000m.', 49000, 0.27, 2.45, ARRAY['spikes', 'moving', 'conveyor', 'springs']::TEXT[]),
(50, '👑 CHEFÃO FINAL: O Guardião Supremo do Zênite', 'cosmos', 'A BATALHA DEFINITIVA AOS 50.000m! O Guardião Supremo do Zênite combina os poderes de todos os 10 mundos do JumpBall!', 50000, 0.25, 2.5, ARRAY['moving', 'springs', 'fragile', 'conveyor']::TEXT[]),
(51, 'Trilhas de Cobre Subatômico', 'quantum_core', 'Desafio temático nos 51.000m de altitude! Domine as plataformas com reflexos aguçados.', 51000, 0.27, 2.31, ARRAY['conveyor', 'lasers']::TEXT[]),
(52, 'Barramento de Dados Taquiônico', 'quantum_core', 'Desafio temático nos 52.000m de altitude! Domine as plataformas com reflexos aguçados.', 52000, 0.28, 2.32, ARRAY['moving', 'conveyor']::TEXT[]),
(53, 'Matriz de Memória Quântica', 'quantum_core', 'Desafio temático nos 53.000m de altitude! Domine as plataformas com reflexos aguçados.', 53000, 0.29, 2.33, ARRAY['fragile', 'moving']::TEXT[]),
(54, 'Labirinto de Feixes Laser', 'quantum_core', 'Desafio temático nos 54.000m de altitude! Domine as plataformas com reflexos aguçados.', 54000, 0.3, 2.34, ARRAY['lasers', 'moving', 'springs']::TEXT[]),
(55, '👑 CHEFÃO 11: Nexus Quântico 9000', 'quantum_core', 'BATALHA DE CHEFÃO AOS 55.000m! Derrote Nexus Quântico 9000!', 55000, 0.31, 2.35, ARRAY['lasers', 'conveyor', 'moving', 'fragile']::TEXT[]),
(56, 'Entrada do Desfiladeiro Seco', 'wild_west', 'Desafio temático nos 56.000m de altitude! Domine as plataformas com reflexos aguçados.', 56000, 0.32, 2.36, ARRAY['wind']::TEXT[]),
(57, 'Saloon Abandonado de Madeira', 'wild_west', 'Desafio temático nos 57.000m de altitude! Domine as plataformas com reflexos aguçados.', 57000, 0.33, 2.37, ARRAY['fragile', 'moving']::TEXT[]),
(58, 'Mina de Ouro Assombrada', 'wild_west', 'Desafio temático nos 58.000m de altitude! Domine as plataformas com reflexos aguçados.', 58000, 0.34, 2.38, ARRAY['spikes', 'fragile']::TEXT[]),
(59, 'Ponte Pênsil da Ravina', 'wild_west', 'Desafio temático nos 59.000m de altitude! Domine as plataformas com reflexos aguçados.', 59000, 0.35, 2.39, ARRAY['wind', 'moving', 'fragile']::TEXT[]),
(60, '👑 CHEFÃO 12: Pistoleiro Espectral', 'wild_west', 'BATALHA DE CHEFÃO AOS 60.000m! Derrote Pistoleiro Espectral!', 60000, 0.26, 2.4, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(61, 'Selva Primordial dos Sauropodes', 'dinosaur', 'Desafio temático nos 61.000m de altitude! Domine as plataformas com reflexos aguçados.', 61000, 0.27, 2.41, ARRAY['moving']::TEXT[]),
(62, 'Pântano dos Fósseis Vivos', 'dinosaur', 'Desafio temático nos 62.000m de altitude! Domine as plataformas com reflexos aguçados.', 62000, 0.28, 2.42, ARRAY['fragile', 'springs']::TEXT[]),
(63, 'Ninho dos Velocirraptores', 'dinosaur', 'Desafio temático nos 63.000m de altitude! Domine as plataformas com reflexos aguçados.', 63000, 0.29, 2.43, ARRAY['moving', 'fragile']::TEXT[]),
(64, 'Garganta dos Pterossauros', 'dinosaur', 'Desafio temático nos 64.000m de altitude! Domine as plataformas com reflexos aguçados.', 64000, 0.3, 2.44, ARRAY['wind', 'moving', 'springs']::TEXT[]),
(65, '👑 CHEFÃO 13: T-Rex Titânico Apex', 'dinosaur', 'BATALHA DE CHEFÃO AOS 65.000m! Derrote T-Rex Titânico Apex!', 65000, 0.31, 2.45, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(66, 'Ágora de Atenas em Mármore', 'olympus', 'Desafio temático nos 66.000m de altitude! Domine as plataformas com reflexos aguçados.', 66000, 0.32, 2.46, ARRAY['springs']::TEXT[]),
(67, 'Colunas Quebradas do Partenon', 'olympus', 'Desafio temático nos 67.000m de altitude! Domine as plataformas com reflexos aguçados.', 67000, 0.33, 2.47, ARRAY['fragile', 'moving']::TEXT[]),
(68, 'Labirinto Subterrâneo de Creta', 'olympus', 'Desafio temático nos 68.000m de altitude! Domine as plataformas com reflexos aguçados.', 68000, 0.34, 2.48, ARRAY['spikes', 'conveyor']::TEXT[]),
(69, 'Portão Dourado do Monte Olimpo', 'olympus', 'Desafio temático nos 69.000m de altitude! Domine as plataformas com reflexos aguçados.', 69000, 0.35, 2.49, ARRAY['moving', 'springs', 'fragile']::TEXT[]),
(70, '👑 CHEFÃO 14: Minotauro de Bronze', 'olympus', 'BATALHA DE CHEFÃO AOS 70.000m! Derrote Minotauro de Bronze!', 70000, 0.26, 2.5, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(71, 'Mega-Rampa do Skate Park Aéreo', 'sports', 'Desafio temático nos 71.000m de altitude! Domine as plataformas com reflexos aguçados.', 71000, 0.27, 2.51, ARRAY['conveyor', 'springs']::TEXT[]),
(72, 'Circuito da Ginástica Gravitacional', 'sports', 'Desafio temático nos 72.000m de altitude! Domine as plataformas com reflexos aguçados.', 72000, 0.28, 2.52, ARRAY['springs', 'moving']::TEXT[]),
(73, 'Pista de Bobsled Congelada', 'sports', 'Desafio temático nos 73.000m de altitude! Domine as plataformas com reflexos aguçados.', 73000, 0.29, 2.53, ARRAY['ice_slick', 'wind', 'moving']::TEXT[]),
(74, 'Velódromo das Alturas', 'sports', 'Desafio temático nos 74.000m de altitude! Domine as plataformas com reflexos aguçados.', 74000, 0.3, 2.54, ARRAY['conveyor', 'moving', 'fragile']::TEXT[]),
(75, '👑 CHEFÃO 15: Gladiador Campeão Titã', 'sports', 'BATALHA DE CHEFÃO AOS 75.000m! Derrote Gladiador Campeão Titã!', 75000, 0.31, 2.55, ARRAY['conveyor', 'moving', 'springs']::TEXT[]),
(76, 'Alameda das Frigideiras Ardentes', 'gastronomy', 'Desafio temático nos 76.000m de altitude! Domine as plataformas com reflexos aguçados.', 76000, 0.32, 2.56, ARRAY['fragile', 'moving']::TEXT[]),
(77, 'Caldeirão dos Caldos Efervescentes', 'gastronomy', 'Desafio temático nos 77.000m de altitude! Domine as plataformas com reflexos aguçados.', 77000, 0.33, 2.57, ARRAY['springs', 'moving']::TEXT[]),
(78, 'Esteira Industrial de Especiarias', 'gastronomy', 'Desafio temático nos 78.000m de altitude! Domine as plataformas com reflexos aguçados.', 78000, 0.34, 2.58, ARRAY['conveyor', 'fragile']::TEXT[]),
(79, 'Fornalha das Grelhas de Basalto', 'gastronomy', 'Desafio temático nos 79.000m de altitude! Domine as plataformas com reflexos aguçados.', 79000, 0.35, 2.59, ARRAY['moving', 'spikes', 'fragile']::TEXT[]),
(80, '👑 CHEFÃO 16: Chef Magmático Vulcânico', 'gastronomy', 'BATALHA DE CHEFÃO AOS 80.000m! Derrote Chef Magmático Vulcânico!', 80000, 0.26, 2.6, ARRAY['conveyor', 'moving', 'fragile']::TEXT[]),
(81, 'Hélice Dupla de DNA Primordial', 'health', 'Desafio temático nos 81.000m de altitude! Domine as plataformas com reflexos aguçados.', 81000, 0.27, 2.61, ARRAY['moving']::TEXT[]),
(82, 'Corrente dos Anticorpos Velozes', 'health', 'Desafio temático nos 82.000m de altitude! Domine as plataformas com reflexos aguçados.', 82000, 0.28, 2.62, ARRAY['moving', 'fragile']::TEXT[]),
(83, 'Ventrículo dos Pulsos Cardíacos', 'health', 'Desafio temático nos 83.000m de altitude! Domine as plataformas com reflexos aguçados.', 83000, 0.29, 2.63, ARRAY['springs', 'moving']::TEXT[]),
(84, 'Sinapse das Fibras Nervosas', 'health', 'Desafio temático nos 84.000m de altitude! Domine as plataformas com reflexos aguçados.', 84000, 0.3, 2.64, ARRAY['lasers', 'moving', 'springs']::TEXT[]),
(85, '👑 CHEFÃO 17: Patógeno Quântico Alfa', 'health', 'BATALHA DE CHEFÃO AOS 85.000m! Derrote Patógeno Quântico Alfa!', 85000, 0.31, 2.65, ARRAY['lasers', 'moving', 'fragile']::TEXT[]),
(86, 'Camada de Ozônio Iônica', 'sky_realm', 'Desafio temático nos 86.000m de altitude! Domine as plataformas com reflexos aguçados.', 86000, 0.32, 2.66, ARRAY['wind']::TEXT[]),
(87, 'Cortina da Aurora Boreal Polar', 'sky_realm', 'Desafio temático nos 87.000m de altitude! Domine as plataformas com reflexos aguçados.', 87000, 0.33, 2.67, ARRAY['moving', 'springs']::TEXT[]),
(88, 'Nuvem Cumulonimbus de Granizo', 'sky_realm', 'Desafio temático nos 88.000m de altitude! Domine as plataformas com reflexos aguçados.', 88000, 0.34, 2.68, ARRAY['ice_slick', 'fragile', 'wind']::TEXT[]),
(89, 'Turbulência do Vórtice Polar', 'sky_realm', 'Desafio temático nos 89.000m de altitude! Domine as plataformas com reflexos aguçados.', 89000, 0.35, 2.69, ARRAY['wind', 'moving', 'fragile']::TEXT[]),
(90, '👑 CHEFÃO 18: Fênix das Tempestades', 'sky_realm', 'BATALHA DE CHEFÃO AOS 90.000m! Derrote Fênix das Tempestades!', 90000, 0.26, 2.7, ARRAY['wind', 'moving', 'fragile', 'springs']::TEXT[]),
(91, 'Grande Muralha das Cordilheiras', 'continents', 'Desafio temático nos 91.000m de altitude! Domine as plataformas com reflexos aguçados.', 91000, 0.27, 2.71, ARRAY['moving']::TEXT[]),
(92, 'Pirâmides Esculpidas dos Andes', 'continents', 'Desafio temático nos 92.000m de altitude! Domine as plataformas com reflexos aguçados.', 92000, 0.28, 2.72, ARRAY['fragile', 'springs']::TEXT[]),
(93, 'Cânions Vermelhos da Austrália', 'continents', 'Desafio temático nos 93.000m de altitude! Domine as plataformas com reflexos aguçados.', 93000, 0.29, 2.73, ARRAY['wind', 'moving']::TEXT[]),
(94, 'Fiordes Glaciais da Escandinávia', 'continents', 'Desafio temático nos 94.000m de altitude! Domine as plataformas com reflexos aguçados.', 94000, 0.3, 2.74, ARRAY['ice_slick', 'moving', 'fragile']::TEXT[]),
(95, '👑 CHEFÃO 19: Esfinge Imperial Global', 'continents', 'BATALHA DE CHEFÃO AOS 95.000m! Derrote Esfinge Imperial Global!', 95000, 0.31, 2.75, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(96, 'Horizonte de Eventos Quântico', 'futuristic', 'Desafio temático nos 96.000m de altitude! Domine as plataformas com reflexos aguçados.', 96000, 0.32, 2.76, ARRAY['conveyor', 'moving']::TEXT[]),
(97, 'Fenda do Hiperespaço 100k', 'futuristic', 'Desafio temático nos 97.000m de altitude! Domine as plataformas com reflexos aguçados.', 97000, 0.33, 2.77, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(98, 'Rede Neural das Constelações', 'futuristic', 'Desafio temático nos 98.000m de altitude! Domine as plataformas com reflexos aguçados.', 98000, 0.34, 2.78, ARRAY['conveyor', 'lasers', 'moving']::TEXT[]),
(99, 'Vórtice Cronológico Pré-Zênite', 'futuristic', 'Desafio temático nos 99.000m de altitude! Domine as plataformas com reflexos aguçados.', 99000, 0.35, 2.79, ARRAY['moving', 'fragile', 'lasers', 'springs']::TEXT[]),
(100, '👑 CHEFÃO 20: Chronos, O Senhor das Eras', 'futuristic', 'BATALHA DE CHEFÃO AOS 100.000m! Derrote Chronos, O Senhor das Eras!', 100000, 0.26, 2.8, ARRAY['moving', 'springs', 'fragile', 'conveyor', 'lasers']::TEXT[]),
(101, 'Abismo Mariana: Nível 1', 'ocean', 'Escalada extrema na estratosfera aos 101.000m!', 101000, 0.32, 3.14, ARRAY['fragile', 'conveyor']::TEXT[]),
(102, 'Abismo Mariana: Nível 2', 'ocean', 'Escalada extrema na estratosfera aos 102.000m!', 102000, 0.33, 3.15, ARRAY['moving', 'springs']::TEXT[]),
(103, 'Abismo Mariana: Nível 3', 'ocean', 'Escalada extrema na estratosfera aos 103.000m!', 103000, 0.34, 3.16, ARRAY['fragile', 'conveyor']::TEXT[]),
(104, 'Abismo Mariana: Nível 4', 'ocean', 'Escalada extrema na estratosfera aos 104.000m!', 104000, 0.24, 3.17, ARRAY['moving', 'springs']::TEXT[]),
(105, '👑 CHEFÃO 21: Kraken Abissal de Neon', 'ocean', 'BATALHA DE CHEFÃO AOS 105.000m! Supere Kraken Abissal de Neon!', 105000, 0.26, 3.18, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(106, 'Cristais de Fogo: Nível 1', 'crystal', 'Escalada extrema na estratosfera aos 106.000m!', 106000, 0.27, 3.19, ARRAY['fragile', 'conveyor']::TEXT[]),
(107, 'Cristais de Fogo: Nível 2', 'crystal', 'Escalada extrema na estratosfera aos 107.000m!', 107000, 0.28, 3.2, ARRAY['moving', 'springs']::TEXT[]),
(108, 'Cristais de Fogo: Nível 3', 'crystal', 'Escalada extrema na estratosfera aos 108.000m!', 108000, 0.3, 3.21, ARRAY['fragile', 'conveyor']::TEXT[]),
(109, 'Cristais de Fogo: Nível 4', 'crystal', 'Escalada extrema na estratosfera aos 109.000m!', 109000, 0.32, 3.22, ARRAY['moving', 'springs']::TEXT[]),
(110, '👑 CHEFÃO 22: Escorpião de Cristal Solar', 'crystal', 'BATALHA DE CHEFÃO AOS 110.000m! Supere Escorpião de Cristal Solar!', 110000, 0.33, 3.23, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(111, 'Acelerador Hádrons: Nível 1', 'quantum', 'Escalada extrema na estratosfera aos 111.000m!', 111000, 0.34, 3.24, ARRAY['fragile', 'conveyor']::TEXT[]),
(112, 'Acelerador Hádrons: Nível 2', 'quantum', 'Escalada extrema na estratosfera aos 112.000m!', 112000, 0.24, 3.25, ARRAY['moving', 'springs']::TEXT[]),
(113, 'Acelerador Hádrons: Nível 3', 'quantum', 'Escalada extrema na estratosfera aos 113.000m!', 113000, 0.26, 3.25, ARRAY['fragile', 'conveyor']::TEXT[]),
(114, 'Acelerador Hádrons: Nível 4', 'quantum', 'Escalada extrema na estratosfera aos 114.000m!', 114000, 0.27, 3.26, ARRAY['moving', 'springs']::TEXT[]),
(115, '👑 CHEFÃO 23: Bóson Descontrolado', 'quantum', 'BATALHA DE CHEFÃO AOS 115.000m! Supere Bóson Descontrolado!', 115000, 0.28, 3.27, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(116, 'Ninho Pterodáctilo: Nível 1', 'dinosaur', 'Escalada extrema na estratosfera aos 116.000m!', 116000, 0.3, 3.28, ARRAY['fragile', 'conveyor']::TEXT[]),
(117, 'Ninho Pterodáctilo: Nível 2', 'dinosaur', 'Escalada extrema na estratosfera aos 117.000m!', 117000, 0.32, 3.29, ARRAY['moving', 'springs']::TEXT[]),
(118, 'Ninho Pterodáctilo: Nível 3', 'dinosaur', 'Escalada extrema na estratosfera aos 118.000m!', 118000, 0.33, 3.3, ARRAY['fragile', 'conveyor']::TEXT[]),
(119, 'Ninho Pterodáctilo: Nível 4', 'dinosaur', 'Escalada extrema na estratosfera aos 119.000m!', 119000, 0.34, 3.31, ARRAY['moving', 'springs']::TEXT[]),
(120, '👑 CHEFÃO 24: Quetzalcoatlus Supremo', 'dinosaur', 'BATALHA DE CHEFÃO AOS 120.000m! Supere Quetzalcoatlus Supremo!', 120000, 0.24, 3.32, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(121, 'Trem Fantasma Oeste: Nível 1', 'wild_west', 'Escalada extrema na estratosfera aos 121.000m!', 121000, 0.26, 3.33, ARRAY['fragile', 'conveyor']::TEXT[]),
(122, 'Trem Fantasma Oeste: Nível 2', 'wild_west', 'Escalada extrema na estratosfera aos 122.000m!', 122000, 0.27, 3.34, ARRAY['moving', 'springs']::TEXT[]),
(123, 'Trem Fantasma Oeste: Nível 3', 'wild_west', 'Escalada extrema na estratosfera aos 123.000m!', 123000, 0.28, 3.35, ARRAY['fragile', 'conveyor']::TEXT[]),
(124, 'Trem Fantasma Oeste: Nível 4', 'wild_west', 'Escalada extrema na estratosfera aos 124.000m!', 124000, 0.3, 3.36, ARRAY['moving', 'springs']::TEXT[]),
(125, '👑 CHEFÃO 25: Locomotiva Blindada Fantasma', 'wild_west', 'BATALHA DE CHEFÃO AOS 125.000m! Supere Locomotiva Blindada Fantasma!', 125000, 0.32, 3.37, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(126, 'Parkour Gravidade 0: Nível 1', 'sports', 'Escalada extrema na estratosfera aos 126.000m!', 126000, 0.33, 3.38, ARRAY['fragile', 'conveyor']::TEXT[]),
(127, 'Parkour Gravidade 0: Nível 2', 'sports', 'Escalada extrema na estratosfera aos 127.000m!', 127000, 0.34, 3.39, ARRAY['moving', 'springs']::TEXT[]),
(128, 'Parkour Gravidade 0: Nível 3', 'sports', 'Escalada extrema na estratosfera aos 128.000m!', 128000, 0.24, 3.39, ARRAY['fragile', 'conveyor']::TEXT[]),
(129, 'Parkour Gravidade 0: Nível 4', 'sports', 'Escalada extrema na estratosfera aos 129.000m!', 129000, 0.26, 3.4, ARRAY['moving', 'springs']::TEXT[]),
(130, '👑 CHEFÃO 26: Campeão da Gravidade Zero', 'sports', 'BATALHA DE CHEFÃO AOS 130.000m! Supere Campeão da Gravidade Zero!', 130000, 0.27, 3.41, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(131, 'Doce do Apocalipse: Nível 1', 'candy', 'Escalada extrema na estratosfera aos 131.000m!', 131000, 0.28, 3.42, ARRAY['fragile', 'conveyor']::TEXT[]),
(132, 'Doce do Apocalipse: Nível 2', 'candy', 'Escalada extrema na estratosfera aos 132.000m!', 132000, 0.3, 3.43, ARRAY['moving', 'springs']::TEXT[]),
(133, 'Doce do Apocalipse: Nível 3', 'candy', 'Escalada extrema na estratosfera aos 133.000m!', 133000, 0.32, 3.44, ARRAY['fragile', 'conveyor']::TEXT[]),
(134, 'Doce do Apocalipse: Nível 4', 'candy', 'Escalada extrema na estratosfera aos 134.000m!', 134000, 0.33, 3.45, ARRAY['moving', 'springs']::TEXT[]),
(135, '👑 CHEFÃO 27: Gólem de Caramelo Ardente', 'candy', 'BATALHA DE CHEFÃO AOS 135.000m! Supere Gólem de Caramelo Ardente!', 135000, 0.34, 3.46, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(136, 'Mente Quântica: Nível 1', 'health', 'Escalada extrema na estratosfera aos 136.000m!', 136000, 0.24, 3.47, ARRAY['fragile', 'conveyor']::TEXT[]),
(137, 'Mente Quântica: Nível 2', 'health', 'Escalada extrema na estratosfera aos 137.000m!', 137000, 0.26, 3.48, ARRAY['moving', 'springs']::TEXT[]),
(138, 'Mente Quântica: Nível 3', 'health', 'Escalada extrema na estratosfera aos 138.000m!', 138000, 0.27, 3.49, ARRAY['fragile', 'conveyor']::TEXT[]),
(139, 'Mente Quântica: Nível 4', 'health', 'Escalada extrema na estratosfera aos 139.000m!', 139000, 0.28, 3.5, ARRAY['moving', 'springs']::TEXT[]),
(140, '👑 CHEFÃO 28: Sinapse Hiperativa Omega', 'health', 'BATALHA DE CHEFÃO AOS 140.000m! Supere Sinapse Hiperativa Omega!', 140000, 0.3, 3.51, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(141, 'Muralha das Eras: Nível 1', 'continents', 'Escalada extrema na estratosfera aos 141.000m!', 141000, 0.32, 3.52, ARRAY['fragile', 'conveyor']::TEXT[]),
(142, 'Muralha das Eras: Nível 2', 'continents', 'Escalada extrema na estratosfera aos 142.000m!', 142000, 0.33, 3.53, ARRAY['moving', 'springs']::TEXT[]),
(143, 'Muralha das Eras: Nível 3', 'continents', 'Escalada extrema na estratosfera aos 143.000m!', 143000, 0.34, 3.53, ARRAY['fragile', 'conveyor']::TEXT[]),
(144, 'Muralha das Eras: Nível 4', 'continents', 'Escalada extrema na estratosfera aos 144.000m!', 144000, 0.24, 3.54, ARRAY['moving', 'springs']::TEXT[]),
(145, '👑 CHEFÃO 29: Colosso das Sete Civilizações', 'continents', 'BATALHA DE CHEFÃO AOS 145.000m! Supere Colosso das Sete Civilizações!', 145000, 0.26, 3.55, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(146, 'Zênite Infinito 150k: Nível 1', 'cosmos', 'Escalada extrema na estratosfera aos 146.000m!', 146000, 0.27, 3.56, ARRAY['fragile', 'conveyor']::TEXT[]),
(147, 'Zênite Infinito 150k: Nível 2', 'cosmos', 'Escalada extrema na estratosfera aos 147.000m!', 147000, 0.28, 3.57, ARRAY['moving', 'springs']::TEXT[]),
(148, 'Zênite Infinito 150k: Nível 3', 'cosmos', 'Escalada extrema na estratosfera aos 148.000m!', 148000, 0.3, 3.58, ARRAY['fragile', 'conveyor']::TEXT[]),
(149, 'Zênite Infinito 150k: Nível 4', 'cosmos', 'Escalada extrema na estratosfera aos 149.000m!', 149000, 0.32, 3.59, ARRAY['moving', 'springs']::TEXT[]),
(150, '👑 CHEFÃO 30: O Demiurgo Eterno do Cosmos', 'cosmos', 'BATALHA DE CHEFÃO AOS 150.000m! Supere O Demiurgo Eterno do Cosmos!', 150000, 0.33, 3.6, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[])
ON CONFLICT (stage_number) DO UPDATE SET
  title = EXCLUDED.title,
  theme = EXCLUDED.theme,
  description = EXCLUDED.description,
  target_height = EXCLUDED.target_height,
  gravity = EXCLUDED.gravity,
  speed_factor = EXCLUDED.speed_factor,
  obstacle_types = EXCLUDED.obstacle_types;
