-- ==============================================================================
-- JUMPBALL: INSERÇÃO E ATUALIZAÇÃO DAS 50 FASES OFICIAIS DO JOGO
-- ==============================================================================

INSERT INTO public.stages (stage_number, title, theme, description, target_height, gravity, speed_factor, obstacle_types)
VALUES
(1, 'Floresta Esmeralda', 'forest', 'Brisa calma e plataformas naturais de carvalho. Perfeita para calibrar o giroscópio e câmera.', 1800, 0.32, 1, ARRAY[]::TEXT[]),
(2, 'Dunas do Saara', 'desert', 'Vento lateral que sopra as dunas. Algumas plataformas de areia desmoronam ao pisar!', 2400, 0.33, 1.1, ARRAY['fragile']),
(3, 'Abismo Oceânico', 'ocean', 'Pressão abissal e alta flutuabilidade. Bolhas gigantes garantem saltos acrobáticos.', 3000, 0.28, 1.15, ARRAY['springs']),
(4, 'Cânion Trovejante', 'storm', 'Tempestades de raios iluminam o cânion. Plataformas condutoras aceleram a subida.', 3600, 0.35, 1.25, ARRAY['moving', 'fragile']),
(5, '👑 CHEFÃO 1: Silvano, Titã da Mata', 'forest', 'BATALHA DE CHEFÃO! Silvano, o Titã da Floresta, arremessa galhos e vinhas espinhosas. Pule nas baterias energéticas para vencê-lo!', 4200, 0.36, 1.35, ARRAY['fragile', 'moving']),
(6, 'Glaciar Ártico', 'arctic', 'Gelo escorregadio e rajadas de nevasca congelante. Mantenha o equilíbrio do celular.', 4800, 0.34, 1.45, ARRAY['ice_slick', 'wind', 'moving']),
(7, 'Caverna de Cristais', 'crystal', 'Prismas luminosos refletem feixes energéticos. Portais de dobra espacial entre plataformas.', 5400, 0.32, 1.55, ARRAY['teleport', 'moving', 'springs']),
(8, 'Santuário Celeste', 'sky', 'Acima das nuvens o ar rarefeito exige passos leves em plataformas etéreas.', 6000, 0.29, 1.65, ARRAY['disappearing', 'springs']),
(9, 'Metrópole Cyberpunk', 'cyberpunk', 'Arranha-céus futuristas com esteiras de alta velocidade e feixes de laser verticais.', 7000, 0.39, 1.85, ARRAY['conveyor', 'lasers', 'moving', 'fragile']),
(10, '👑 CHEFÃO 2: Faraó de Pedra de Rá', 'pyramids', 'BATALHA DE CHEFÃO! O guardião milenar desperta em sua pirâmide cósmica lançando escaravelhos e tempestades de arenito.', 8500, 0.33, 1.8, ARRAY['moving', 'fragile']),
(11, 'Cachoeira Ancestral', 'waterfall', 'Cascatas majestosas e bruma refrescante. O fluxo das águas cria correntes e molas que impulsionam os saltos.', 9500, 0.33, 1.35, ARRAY['moving', 'springs']),
(12, 'Floresta Sagrada Indígena', 'indigenous', 'Totens ancestrais rúnicos e espíritos da mata protegem a subida sagrada entre copas de árvores milenares.', 10500, 0.31, 1.45, ARRAY['springs', 'fragile', 'moving']),
(13, 'Tempestade de Monção', 'rain', 'Chuva torrencial contínua e rajadas de vento tempestuoso que desviam a bola com força lateral constante.', 11600, 0.35, 1.5, ARRAY['moving', 'fragile']),
(14, 'Tundra Congelada do Inverno', 'winter', 'Nevasca polar cortante e plataformas cristalinas de gelo eterno com inércia contínua e derrapagem intensa.', 12800, 0.36, 1.55, ARRAY['moving', 'fragile']),
(15, '👑 CHEFÃO 3: Leviatã das Marés', 'ocean', 'BATALHA DE CHEFÃO! A criatura colossal das fossas oceânicas invoca jatos d''água torrenciais e águas-vivas elétricas.', 14000, 0.3, 1.65, ARRAY['moving', 'springs']),
(16, 'Cidadela Flutuante dos Céus', 'ruins', 'Templos e colunas místicas levitando na estratosfera. Fragmentos antigravitacionais geram saltos flutuantes.', 15200, 0.28, 1.7, ARRAY['moving', 'springs', 'fragile']),
(17, 'Fenda Vulcânica de Obsidiana', 'obsidian', 'O abismo tectônico mais profundo e perigoso. Rochas de obsidiana incandescentes deslizam sobre rios de magma vivo.', 16500, 0.4, 1.8, ARRAY['moving', 'conveyor', 'fragile']),
(18, 'Tempestade Solar Corona', 'solar', 'Na coroa incandescente de uma estrela colossal. Proeminências de plasma e ventos solares de milhões de graus.', 17800, 0.32, 1.9, ARRAY['moving', 'fragile', 'springs']),
(19, 'Cinturão de Asteroides', 'asteroid', 'Campos densos de meteoritos em rotação contínua e poeira cósmica violeta. Pise com precisão cirúrgica.', 19000, 0.27, 2, ARRAY['moving', 'fragile', 'conveyor']),
(20, '👑 CHEFÃO 4: Colosso dos Relâmpagos', 'storm', 'BATALHA DE CHEFÃO! Um titã de alta voltagem descarrega tempestades de raios contínuas no topo do cânion.', 20000, 0.32, 2, ARRAY['moving', 'fragile']),
(21, 'Monte Olimpo dos Deuses', 'olympus', 'O santuário dos deuses helênicos. Colunas coríntias de mármore dourado suspensas em nuvens etéreas.', 21000, 0.29, 1.6, ARRAY['springs', 'moving']),
(22, 'Estádio dos Campeões', 'soccer', 'Uma arena de futebol monumental sob os holofotes! O gramado sintético perfeito para arrancadas de glória.', 22000, 0.33, 1.65, ARRAY['moving', 'springs']),
(23, 'Nau dos Mares Tempestuosos', 'ship', 'No convés e mastros de um galeão lendário navegando por ondas oceânicas bravias e ventos marinhos fortes.', 23000, 0.3, 1.7, ARRAY['moving', 'fragile']),
(24, 'Primavera das Cerejeiras', 'spring_season', 'Chuva suave de pétalas de sakura cor-de-rosa sob um céu oriental primaveril de serenidade absoluta.', 24000, 0.27, 1.5, ARRAY['springs']),
(25, '👑 CHEFÃO 5: Gólem Glacial de Neve', 'arctic', 'BATALHA DE CHEFÃO! O soberano do zero absoluto tenta congelar seus saltos com chuvas de estalactites pontiagudas.', 25000, 0.33, 1.7, ARRAY['moving', 'fragile']),
(26, 'Multiverso dos Heróis', 'heroes', 'O epicentro das lendas heroicas! Raios de poder cósmico, escudos de vibranium e energia cinética épica.', 26000, 0.3, 1.8, ARRAY['springs', 'conveyor', 'moving']),
(27, 'Córtex da Placa-Mãe', 'computer', 'Caminhe pelas trilhas de cobre impresso, processadores quânticos e barramentos de fibra de alta frequência.', 27000, 0.32, 1.85, ARRAY['conveyor', 'moving']),
(28, 'Sinfonia das Estrelas', 'music', 'Partituras estelares flutuantes, teclas de piano holográficas e acordes musicais ressoando no vácuo.', 28000, 0.28, 1.7, ARRAY['springs', 'fragile']),
(29, 'Teia da Ciber-Rede', 'internet', 'A malha de satélites e nós de fibra da rede mundial. Pacotes de dados trafegando na velocidade da luz.', 29000, 0.3, 1.9, ARRAY['moving', 'conveyor']),
(30, '👑 CHEFÃO 6: Dragão Solar de Magma', 'volcano', 'BATALHA DE CHEFÃO! A lendária serpente de fogo desperta do coração do vulcão cospindo rochas incandescentes.', 30000, 0.36, 2, ARRAY['lava_rising', 'moving', 'fragile']),
(31, 'Cubo Mágico Tridimensional', 'magic_cube', 'Um labirinto cósmico de cubos coloridos 3x3x3 que giram e reconfiguram suas faces em tempo real.', 31000, 0.29, 1.95, ARRAY['moving', 'conveyor', 'fragile']),
(32, 'Reino Doce de Confeitos', 'candy', 'Montanhas de marshmallow, bengalas doces de hortelã e nuvens de algodão-doce açucarado.', 32000, 0.28, 1.75, ARRAY['springs', 'fragile']),
(33, 'Covil do Dragão de Fogo', 'dragon', 'Nas profundezas da caverna do dragão ancestral, onde rios de ouro fundido banham estalagmites incandescentes.', 33000, 0.35, 2, ARRAY['moving', 'fragile']),
(34, 'Fliperama Pixel 8-Bit', 'arcade', 'Uma homenagem nostálgica aos arcades clássicos dos anos 80 com gráficos pixelados e sintetizadores chiptune.', 34000, 0.32, 2, ARRAY['conveyor', 'springs']),
(35, '👑 CHEFÃO 7: Overlord IA Matrix', 'cyberpunk', 'BATALHA DE CHEFÃO! A inteligência artificial suprema da metrópole aciona esteiras aceleradoras e feixes de laser verticais.', 35000, 0.34, 2.1, ARRAY['conveyor', 'moving', 'fragile']),
(36, 'Véu da Aurora Boreal', 'aurora', 'Faixas ondulantes de plasma magnético verde-esmeralda e violeta cortando o céu glacial polar.', 36000, 0.26, 1.8, ARRAY['springs', 'moving']),
(37, 'Parque de Diversões Cósmico', 'carnival', 'Roda-gigante cósmica, montanha-russa gravitacional e tendas mágicas iluminadas por milhares de lâmpadas neon.', 37000, 0.31, 2.1, ARRAY['moving', 'springs', 'conveyor']),
(38, 'Pirâmides do Egito Ancestral', 'pyramids', 'Monumentos imortais no deserto dos faraós. Hieróglifos gravados em blocos de calcário dourado sob o Sol de Rá.', 38000, 0.34, 2.15, ARRAY['fragile', 'moving']),
(39, 'Fábrica Steampunk de Bronze', 'steampunk', 'Caldeiras titânicas, manômetros a vapor, pistões de cobre e engrenagens gigantescas em rotação contínua.', 39000, 0.36, 2.2, ARRAY['moving', 'conveyor', 'fragile']),
(40, '👑 CHEFÃO 8: Singularidade Multiversal', 'quantum', 'BATALHA DE CHEFÃO MULTIVERSAL! A Singularidade abre fendas no contínuo espaço-tempo e ENVIA O JOGADOR PARA UM UNIVERSO PARALELO!', 40000, 0.26, 2.3, ARRAY['moving', 'fragile', 'springs']),
(41, 'Pedreira dos Titãs de Rocha', 'rock', 'Paredões ciclópicos de rocha de granito e ardósia. Blocos monolíticos brutos e pedregulhos instáveis.', 41000, 0.35, 2.1, ARRAY['spikes', 'moving', 'fragile']),
(42, 'Fundição de Ferro e Aço', 'iron', 'Vigas maciças de ferro fundido, correntes titânicas e caldeiras incandescentes forjando aço pesado.', 42000, 0.37, 2.2, ARRAY['spikes', 'conveyor', 'moving']),
(43, 'Serraria dos Troncos de Madeira', 'wood', 'Pilhas imensas de toras de madeira de lei, vigas de carvalho maciço e pontes rústicas suspensas.', 43000, 0.31, 2, ARRAY['spikes', 'fragile', 'moving']),
(44, 'Coliseu dos Heróis de Aço', 'heroes', 'A arena dos maiores campeões da galáxia! Estandartes heróicos, símbolos titânicos e desafios de pura bravura.', 44000, 0.33, 2.1, ARRAY['moving', 'springs', 'conveyor']),
(45, '👑 CHEFÃO 9: Autômato Titânico de Bronze', 'steampunk', 'BATALHA DE CHEFÃO! A máquina industrial suprema de bronze gira engrenagens ciclópicas e solta vapor superaquecido.', 45000, 0.35, 2.2, ARRAY['moving', 'fragile', 'conveyor']),
(46, 'Singularidade do Vazio Cósmico', 'singularity', 'O horizonte de eventos de um buraco negro supermassivo. Distorções ópticas gravitacionais atraindo tudo ao centro.', 46000, 0.38, 2.3, ARRAY['moving', 'conveyor', 'fragile']),
(47, 'Muralha do Arcade Retrô', 'arcade', 'Um labirinto nostálgico pixelado com telas CRT, efeitos glitch e plataformas que parecem saídas de clássicos dos anos 80.', 47000, 0.3, 2.35, ARRAY['springs', 'moving', 'conveyor']),
(48, 'Santuário de Aurora Boreal', 'aurora', 'Cortinas etéreas de luz esmeralda e turquesa ondulando nos confins da estratosfera orbital.', 48000, 0.29, 2.2, ARRAY['fragile', 'springs', 'moving']),
(49, 'Vórtice do Tempo Infinito', 'cosmos', 'A penúltima fronteira! Linhas temporais se cruzando em constelações brilhantes rumo à marca de 50.000m.', 49000, 0.27, 2.45, ARRAY['spikes', 'moving', 'conveyor', 'springs']),
(50, '👑 CHEFÃO FINAL: O Guardião Supremo do Zênite', 'cosmos', 'A BATALHA DEFINITIVA AOS 50.000m! O Guardião Supremo do Zênite combina os poderes de todos os 10 mundos do JumpBall!', 50000, 0.25, 2.5, ARRAY['moving', 'springs', 'fragile', 'conveyor'])
ON CONFLICT (stage_number) DO UPDATE SET
  title = EXCLUDED.title,
  theme = EXCLUDED.theme,
  description = EXCLUDED.description,
  target_height = EXCLUDED.target_height,
  gravity = EXCLUDED.gravity,
  speed_factor = EXCLUDED.speed_factor,
  obstacle_types = EXCLUDED.obstacle_types;
