-- ==============================================================================
-- JUMPBALL: INSERÇÃO E ATUALIZAÇÃO DAS 150 FASES OFICIAIS DO JOGO
-- ==============================================================================

INSERT INTO public.stages (stage_number, title, theme, description, target_height, gravity, speed_factor, obstacle_types)
VALUES
(1, 'Floresta Esmeralda', 'forest', 'Brisa calma e plataformas naturais de carvalho. Perfeita para calibrar o giroscópio e câmera.', 1800, 0.32, 1, ARRAY[]::TEXT[]),
(2, 'Dunas do Saara', 'desert', 'Vento lateral que sopra as dunas. Algumas plataformas de areia desmoronam ao pisar!', 2400, 0.33, 1.1, ARRAY['fragile']::TEXT[]),
(3, 'Abismo Oceânico', 'ocean', 'Pressão abissal e alta flutuabilidade. Bolhas gigantes garantem saltos acrobáticos.', 3000, 0.28, 1.15, ARRAY['springs']::TEXT[]),
(4, 'Cânion Trovejante', 'storm', 'Tempestades de raios iluminam o cânion. Plataformas condutoras aceleram a subida.', 3600, 0.35, 1.25, ARRAY['moving', 'fragile']::TEXT[]),
(5, '👑 CHEFÃO 1: Silvano, Titã da Mata', 'forest', 'BATALHA DE CHEFÃO! Silvano, o Titã da Floresta, arremessa galhos e vinhas espinhosas. Pule nas baterias energéticas para vencê-lo!', 4200, 0.36, 1.35, ARRAY['fragile', 'moving']::TEXT[]),
(6, 'Glaciar Ártico', 'arctic', 'Gelo escorregadio e rajadas de nevasca congelante. Mantenha o equilíbrio do celular.', 4800, 0.34, 1.45, ARRAY['ice_slick', 'wind', 'moving']::TEXT[]),
(7, 'Caverna de Cristais', 'crystal', 'Prismas luminosos refletem feixes energéticos. Portais de dobra espacial entre plataformas.', 5400, 0.32, 1.55, ARRAY['teleport', 'moving', 'springs']::TEXT[]),
(8, 'Santuário Celeste', 'sky', 'Acima das nuvens o ar rarefeito exige passos leves em plataformas etéreas.', 6000, 0.29, 1.65, ARRAY['disappearing', 'springs']::TEXT[]),
(9, 'Metrópole Cyberpunk', 'cyberpunk', 'Arranha-céus futuristas com esteiras de alta velocidade e feixes de laser verticais.', 7000, 0.39, 1.85, ARRAY['conveyor', 'lasers', 'moving', 'fragile']::TEXT[]),
(10, '👑 CHEFÃO 2: Faraó de Pedra de Rá', 'pyramids', 'BATALHA DE CHEFÃO! O guardião milenar desperta em sua pirâmide cósmica lançando escaravelhos e tempestades de arenito.', 8500, 0.33, 1.8, ARRAY['moving', 'fragile']::TEXT[]),
(11, 'Cachoeira Ancestral', 'waterfall', 'Cascatas majestosas e bruma refrescante. O fluxo das águas cria correntes e molas que impulsionam os saltos.', 9500, 0.33, 1.35, ARRAY['moving', 'springs']::TEXT[]),
(12, 'Floresta Sagrada Indígena', 'indigenous', 'Totens ancestrais rúnicos e espíritos da mata protegem a subida sagrada entre copas de árvores milenares.', 10500, 0.31, 1.45, ARRAY['springs', 'fragile', 'moving']::TEXT[]),
(13, 'Tempestade de Monção', 'rain', 'Chuva torrencial contínua e rajadas de vento tempestuoso que desviam a bola com força lateral constante.', 11600, 0.35, 1.5, ARRAY['moving', 'fragile']::TEXT[]),
(14, 'Tundra Congelada do Inverno', 'winter', 'Nevasca polar cortante e plataformas cristalinas de gelo eterno com inércia contínua e derrapagem intensa.', 12800, 0.36, 1.55, ARRAY['moving', 'fragile']::TEXT[]),
(15, '👑 CHEFÃO 3: Leviatã das Marés', 'ocean', 'BATALHA DE CHEFÃO! A criatura colossal das fossas oceânicas invoca jatos d''água torrenciais e águas-vivas elétricas.', 14000, 0.3, 1.65, ARRAY['moving', 'springs']::TEXT[]),
(16, 'Cidadela Flutuante dos Céus', 'ruins', 'Templos e colunas místicas levitando na estratosfera. Fragmentos antigravitacionais geram saltos flutuantes.', 15200, 0.28, 1.7, ARRAY['moving', 'springs', 'fragile']::TEXT[]),
(17, 'Fenda Vulcânica de Obsidiana', 'obsidian', 'O abismo tectônico mais profundo e perigoso. Rochas de obsidiana incandescentes deslizam sobre rios de magma vivo.', 16500, 0.4, 1.8, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(18, 'Tempestade Solar Corona', 'solar', 'Na coroa incandescente de uma estrela colossal. Proeminências de plasma e ventos solares de milhões de graus.', 17800, 0.32, 1.9, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(19, 'Cinturão de Asteroides', 'asteroid', 'Campos densos de meteoritos em rotação contínua e poeira cósmica violeta. Pise com precisão cirúrgica.', 19000, 0.27, 2, ARRAY['moving', 'fragile', 'conveyor']::TEXT[]),
(20, '👑 CHEFÃO 4: Colosso dos Relâmpagos', 'storm', 'BATALHA DE CHEFÃO! Um titã de alta voltagem descarrega tempestades de raios contínuas no topo do cânion.', 20000, 0.32, 2, ARRAY['moving', 'fragile']::TEXT[]),
(21, 'Monte Olimpo dos Deuses', 'olympus', 'O santuário dos deuses helênicos. Colunas coríntias de mármore dourado suspensas em nuvens etéreas.', 21000, 0.29, 1.6, ARRAY['springs', 'moving']::TEXT[]),
(22, 'Estádio dos Campeões', 'soccer', 'Uma arena de futebol monumental sob os holofotes! O gramado sintético perfeito para arrancadas de glória.', 22000, 0.33, 1.65, ARRAY['moving', 'springs']::TEXT[]),
(23, 'Nau dos Mares Tempestuosos', 'ship', '🏃‍♂️ PERCURSO HORIZONTAL! Corra pelo convés e mastros de um galeão lendário navegando por ondas oceânicas bravias. Não caia no mar!', 23000, 0.36, 1.7, ARRAY['moving', 'fragile']::TEXT[]),
(24, 'Primavera das Cerejeiras', 'spring_season', 'Chuva suave de pétalas de sakura cor-de-rosa sob um céu oriental primaveril de serenidade absoluta.', 24000, 0.27, 1.5, ARRAY['springs']::TEXT[]),
(25, '👑 CHEFÃO 5: Gólem Glacial de Neve', 'arctic', 'BATALHA DE CHEFÃO! O soberano do zero absoluto tenta congelar seus saltos com chuvas de estalactites pontiagudas.', 25000, 0.33, 1.7, ARRAY['moving', 'fragile']::TEXT[]),
(26, 'Multiverso dos Heróis', 'heroes', 'O epicentro das lendas heroicas! Raios de poder cósmico, escudos de vibranium e energia cinética épica.', 26000, 0.3, 1.8, ARRAY['springs', 'conveyor', 'moving']::TEXT[]),
(27, 'Córtex da Placa-Mãe', 'computer', 'Caminhe pelas trilhas de cobre impresso, processadores quânticos e barramentos de fibra de alta frequência.', 27000, 0.32, 1.85, ARRAY['conveyor', 'moving']::TEXT[]),
(28, 'Sinfonia das Estrelas', 'music', 'Partituras estelares flutuantes, teclas de piano holográficas e acordes musicais ressoando no vácuo.', 28000, 0.28, 1.7, ARRAY['springs', 'fragile']::TEXT[]),
(29, 'Teia da Ciber-Rede', 'internet', 'A malha de satélites e nós de fibra da rede mundial. Pacotes de dados trafegando na velocidade da luz.', 29000, 0.3, 1.9, ARRAY['moving', 'conveyor']::TEXT[]),
(30, '👑 CHEFÃO 6: Dragão Solar de Magma', 'volcano', 'BATALHA DE CHEFÃO! A lendária serpente de fogo desperta do coração do vulcão cospindo rochas incandescentes.', 30000, 0.36, 2, ARRAY['lava_rising', 'moving', 'fragile']::TEXT[]),
(31, 'Cubo Mágico Tridimensional', 'magic_cube', 'Um labirinto cósmico de cubos coloridos 3x3x3 que giram e reconfiguram suas faces em tempo real.', 31000, 0.29, 1.95, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(32, 'Reino Doce de Confeitos', 'candy', 'Montanhas de marshmallow, bengalas doces de hortelã e nuvens de algodão-doce açucarado.', 32000, 0.28, 1.75, ARRAY['springs', 'fragile']::TEXT[]),
(33, 'Covil do Dragão de Fogo', 'dragon', 'Nas profundezas da caverna do dragão ancestral, onde rios de ouro fundido banham estalagmites incandescentes.', 33000, 0.35, 2, ARRAY['moving', 'fragile']::TEXT[]),
(34, 'Fliperama Pixel 8-Bit', 'arcade', 'Uma homenagem nostálgica aos arcades clássicos dos anos 80 com gráficos pixelados e sintetizadores chiptune.', 34000, 0.32, 2, ARRAY['conveyor', 'springs']::TEXT[]),
(35, '👑 CHEFÃO 7: Overlord IA Matrix', 'cyberpunk', 'BATALHA DE CHEFÃO! A inteligência artificial suprema da metrópole aciona esteiras aceleradoras e feixes de laser verticais.', 35000, 0.34, 2.1, ARRAY['conveyor', 'moving', 'fragile']::TEXT[]),
(36, 'Véu da Aurora Boreal', 'aurora', 'Faixas ondulantes de plasma magnético verde-esmeralda e violeta cortando o céu glacial polar.', 36000, 0.26, 1.8, ARRAY['springs', 'moving']::TEXT[]),
(37, 'Parque de Diversões Cósmico', 'carnival', 'Roda-gigante cósmica, montanha-russa gravitacional e tendas mágicas iluminadas por milhares de lâmpadas neon.', 37000, 0.31, 2.1, ARRAY['moving', 'springs', 'conveyor']::TEXT[]),
(38, 'Pirâmides do Egito Ancestral', 'pyramids', 'Monumentos imortais no deserto dos faraós. Hieróglifos gravados em blocos de calcário dourado sob o Sol de Rá.', 38000, 0.34, 2.15, ARRAY['fragile', 'moving']::TEXT[]),
(39, 'Fábrica Steampunk de Bronze', 'steampunk', '🏃‍♂️ PERCURSO HORIZONTAL! Atravesse a fábrica steampunk repleta de caldeiras, pistões de cobre e engrenagens colossais girando!', 39000, 0.38, 2.2, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(40, '👑 CHEFÃO 8: Singularidade Multiversal', 'quantum', 'BATALHA DE CHEFÃO MULTIVERSAL! A Singularidade abre fendas no contínuo espaço-tempo e ENVIA O JOGADOR PARA UM UNIVERSO PARALELO!', 40000, 0.26, 2.3, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(41, 'Pedreira dos Titãs de Rocha', 'rock', 'Paredões ciclópicos de rocha de granito e ardósia. Blocos monolíticos brutos e pedregulhos instáveis.', 41000, 0.35, 2.1, ARRAY['spikes', 'moving', 'fragile']::TEXT[]),
(42, 'Fundição de Ferro e Aço', 'iron', 'Vigas maciças de ferro fundido, correntes titânicas e caldeiras incandescentes forjando aço pesado.', 42000, 0.37, 2.2, ARRAY['spikes', 'conveyor', 'moving']::TEXT[]),
(43, 'Serraria dos Troncos de Madeira', 'wood', 'Pilhas imensas de toras de madeira de lei, vigas de carvalho maciço e pontes rústicas suspensas.', 43000, 0.31, 2, ARRAY['spikes', 'fragile', 'moving']::TEXT[]),
(44, 'Coliseu dos Heróis de Aço', 'heroes', 'A arena dos maiores campeões da galáxia! Estandartes heróicos, símbolos titânicos e desafios de pura bravura.', 44000, 0.33, 2.1, ARRAY['moving', 'springs', 'conveyor']::TEXT[]),
(45, '👑 CHEFÃO 9: Autômato Titânico de Bronze', 'steampunk', 'BATALHA DE CHEFÃO! A máquina industrial suprema de bronze gira engrenagens ciclópicas e solta vapor superaquecido.', 45000, 0.35, 2.2, ARRAY['moving', 'fragile', 'conveyor']::TEXT[]),
(46, 'Singularidade do Vazio Cósmico', 'singularity', 'O horizonte de eventos de um buraco negro supermassivo. Distorções ópticas gravitacionais atraindo tudo ao centro.', 46000, 0.38, 2.3, ARRAY['moving', 'conveyor', 'fragile']::TEXT[]),
(47, 'Muralha do Arcade Retrô', 'arcade', 'Um labirinto nostálgico pixelado com telas CRT, efeitos glitch e plataformas que parecem saídas de clássicos dos anos 80.', 47000, 0.3, 2.35, ARRAY['springs', 'moving', 'conveyor']::TEXT[]),
(48, 'Santuário de Aurora Boreal', 'aurora', 'Cortinas etéreas de luz esmeralda e turquesa ondulando nos confins da estratosfera orbital.', 48000, 0.29, 2.2, ARRAY['fragile', 'springs', 'moving']::TEXT[]),
(49, 'Vórtice do Tempo Infinito', 'cosmos', 'A penúltima fronteira! Linhas temporais se cruzando em constelações brilhantes rumo à marca de 50.000m.', 49000, 0.27, 2.45, ARRAY['spikes', 'moving', 'conveyor', 'springs']::TEXT[]),
(50, '👑 CHEFÃO FINAL: O Guardião Supremo do Zênite', 'cosmos', 'A BATALHA DEFINITIVA AOS 50.000m! O Guardião Supremo do Zênite combina os poderes de todos os 10 mundos do JumpBall!', 50000, 0.25, 2.5, ARRAY['moving', 'springs', 'fragile', 'conveyor']::TEXT[]),
(51, 'Trilhas de Cobre Subatômico', 'quantum_core', 'Salte sobre pistas condutoras de cobre dourado energizadas por pulsos quânticos.', 51000, 0.32, 2.31, ARRAY['springs']::TEXT[]),
(52, 'Barramento Taquiônico', 'quantum_core', 'Fluxos de dados hipervelozes empurram você pelas pontes lógicas da placa-mãe.', 52000, 0.34, 2.33, ARRAY['conveyor', 'moving']::TEXT[]),
(53, 'Matriz de Memória Quântica', 'quantum_core', 'Pise com extrema leveza! Cada bloco de memória só suporta um único cálculo.', 53000, 0.36, 2.34, ARRAY['fragile', 'moving']::TEXT[]),
(54, 'Túnel do Acelerador de Fótons', 'quantum_core', '🏃‍♂️ PERCURSO HORIZONTAL! Dispare em linha reta pelo colisor de fótons desviando de esteiras e prismas!', 54000, 0.26, 2.35, ARRAY['moving', 'conveyor']::TEXT[]),
(55, '👑 CHEFÃO 11: Nexus Quântico 9000', 'quantum_core', 'BATALHA DE CHEFÃO AOS 55.000m! O supercomputador autônomo tenta corromper seu código de salto!', 55000, 0.28, 2.36, ARRAY['moving', 'conveyor', 'spikes']::TEXT[]),
(56, 'Garganta de Arenito Vermelho', 'wild_west', 'O vento uivante do cânion desafia seu equilíbrio entre penhascos alaranjados.', 56000, 0.3, 2.38, ARRAY['wind']::TEXT[]),
(57, 'Saloon Abandonado de Madeira', 'wild_west', 'Salte sobre assoalhos decrépitos de pinho seco do lendário saloon fantasma.', 57000, 0.32, 2.39, ARRAY['fragile', 'moving']::TEXT[]),
(58, 'Mina de Ouro Assombrada', 'wild_west', 'Desça nas galerias esquecidas da mina de ouro onde brotam espinhos de ferro fundido.', 58000, 0.34, 2.4, ARRAY['spikes', 'moving']::TEXT[]),
(59, 'Cavalgada na Ferrovia dos Despenhadeiros', 'wild_west', '🏃‍♂️ PERCURSO HORIZONTAL! Atravesse a ponte férrea de madeira antes que o trem fantasma chegue!', 59000, 0.36, 2.42, ARRAY['fragile', 'moving']::TEXT[]),
(60, '👑 CHEFÃO 12: Pistoleiro Espectral', 'wild_west', 'DUELO AO MEIO-DIA AOS 60.000m! O xerife fantasma não permite intrusos em seu desfiladeiro!', 60000, 0.26, 2.43, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(61, 'Copas das Sequoias Gigantes', 'dinosaur', 'Suba pela vegetação pré-histórica colossal intocada há 150 milhões de anos.', 61000, 0.28, 2.44, ARRAY['springs']::TEXT[]),
(62, 'Pântano dos Fósseis Calcários', 'dinosaur', 'Pise com agilidade extrema nas ossadas ancestrais sobre a lama borbulhante.', 62000, 0.3, 2.46, ARRAY['fragile', 'moving']::TEXT[]),
(63, 'Garganta dos Ninhos de Espinhos', 'dinosaur', 'O ninho das feras está repleto de armadilhas pontiagudas e plataformas instáveis.', 63000, 0.32, 2.47, ARRAY['spikes', 'moving']::TEXT[]),
(64, 'Corrida na Trilha dos Velocirraptores', 'dinosaur', '🏃‍♂️ PERCURSO HORIZONTAL! Corra lateralmente em alta velocidade escapando dos predadores da selva!', 64000, 0.34, 2.48, ARRAY['moving', 'springs']::TEXT[]),
(65, '👑 CHEFÃO 13: T-Rex Titânico Apex', 'dinosaur', 'CONFRONTO PRIMORDIAL AOS 65.000m! Enfrente o rei indiscutível da Era Mesozóica!', 65000, 0.36, 2.49, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(66, 'Ágora de Mármore de Atenas', 'olympus', 'A praça central dos filósofos e generais da Grécia Antiga sob a bênção de Atena.', 66000, 0.26, 2.51, ARRAY['moving']::TEXT[]),
(67, 'Colunas Quebradas do Partenon', 'olympus', 'Escale os vestígios do templo sagrado suspenso nos céus da Hélade.', 67000, 0.28, 2.52, ARRAY['fragile', 'springs']::TEXT[]),
(68, 'Forja Divina de Hefesto', 'olympus', 'A forja onde os raios de Zeus são moldados em bronze celestial e fogo eterno.', 68000, 0.3, 2.53, ARRAY['spikes', 'moving']::TEXT[]),
(69, 'Pátio das Bigas do Monte Olimpo', 'olympus', '🏃‍♂️ PERCURSO HORIZONTAL! Acelere pelo hipódromo dos deuses gregos sobre pistas velozes!', 69000, 0.32, 2.55, ARRAY['conveyor', 'moving']::TEXT[]),
(70, '👑 CHEFÃO 14: Minotauro de Bronze', 'olympus', 'DUELO NO LABIRINTO AOS 70.000m! O colosso taurino de bronze forjado quer esmagar seu avanço!', 70000, 0.34, 2.56, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(71, 'Mega-Rampa do Half-Pipe Aéreo', 'sports', 'Pratique manobras insanas no maior half-pipe suspenso da galáxia esportiva.', 71000, 0.36, 2.57, ARRAY['springs']::TEXT[]),
(72, 'Circuito da Ginástica Rítmica', 'sports', 'Sincronize seus saltos com o ritmo dos holofotes e conquiste notas perfeitas dos jurados.', 72000, 0.26, 2.59, ARRAY['moving', 'fragile']::TEXT[]),
(73, 'Sprint dos 100 Metros Espaciais', 'sports', '🏃‍♂️ PERCURSO HORIZONTAL! Dispare em arrancada pura na pista sintética com cronômetro em tempo real!', 73000, 0.28, 2.6, ARRAY['conveyor', 'springs']::TEXT[]),
(74, 'Velódromo dos Aros de Fogo', 'sports', 'Pedale nas alturas em uma pista oval futurista projetada para quebrar recordes mundiais.', 74000, 0.3, 2.61, ARRAY['conveyor', 'spikes']::TEXT[]),
(75, '👑 CHEFÃO 15: Gladiador Campeão Titã', 'sports', 'FINAL DO CAMPEONATO AOS 75.000m! Prove ser o atleta absoluto sob o olhar de milhões na torcida!', 75000, 0.32, 2.63, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(76, 'Alameda das Frigideiras Ardentes', 'gastronomy', 'Caminhe com cuidado sobre as alças de cobre e chapas quentes da cozinha monumental.', 76000, 0.34, 2.64, ARRAY['moving', 'spikes']::TEXT[]),
(77, 'Caldeirão dos Caldos Efervescentes', 'gastronomy', 'Aproveite a efervescência do caldeirão cósmico para voar mais alto entre conchas douradas.', 77000, 0.36, 2.65, ARRAY['springs', 'fragile']::TEXT[]),
(78, 'Esteira Industrial de Temperos', 'gastronomy', 'Pistas rolantes industriais transportando sacas de açafrão, canela e ervas raras.', 78000, 0.26, 2.66, ARRAY['conveyor', 'moving']::TEXT[]),
(79, 'Esteira dos Confeitos da Grande Cozinha', 'gastronomy', '🏃‍♂️ PERCURSO HORIZONTAL! Corra lateralmente pela bancada do banquete dos deuses gastronômicos!', 79000, 0.28, 2.68, ARRAY['conveyor', 'moving']::TEXT[]),
(80, '👑 CHEFÃO 16: Chef Magmático Vulcânico', 'gastronomy', 'O PRATO PRINCIPAL AOS 80.000m! O mestre cuca do magma quer transformar seu salto em banquete!', 80000, 0.3, 2.69, ARRAY['moving', 'fragile', 'spikes', 'conveyor']::TEXT[]),
(81, 'Hélice Dupla do Código Genético', 'health', 'Suba pela fita de DNA cósmica que guarda as instruções fundamentais da vida eterna.', 81000, 0.32, 2.7, ARRAY['springs']::TEXT[]),
(82, 'Corrente dos Anticorpos Velozes', 'health', 'Desvie dos glóbulos hiperativos que reagem com força a qualquer elemento invasor.', 82000, 0.34, 2.72, ARRAY['moving', 'fragile']::TEXT[]),
(83, 'Ventrículo dos Pulsos Bioelétricos', 'health', 'Sinta a pulsação colossal do núcleo vital e salte exatamente no momento do sístole.', 83000, 0.36, 2.73, ARRAY['spikes', 'springs']::TEXT[]),
(84, 'Artéria Principal da Vida', 'health', '🏃‍♂️ PERCURSO HORIZONTAL! Navegue horizontalmente pela grande artéria em ritmo de alta velocidade!', 84000, 0.26, 2.74, ARRAY['conveyor', 'moving']::TEXT[]),
(85, '👑 CHEFÃO 17: Patógeno Quântico Alfa', 'health', 'QUARANTENA ABSOLUTA AOS 85.000m! Erradique a anomalia microscópica antes que contamine o cosmos!', 85000, 0.28, 2.75, ARRAY['moving', 'fragile', 'spikes', 'springs']::TEXT[]),
(86, 'Camada de Ozônio Ionizada', 'sky_realm', 'Flutue nas franjas do espaço onde o céu se funde com o infinito azul-violeta.', 86000, 0.3, 2.77, ARRAY['springs']::TEXT[]),
(87, 'Nuvem de Granizo Cumulonimbus', 'sky_realm', 'Enfrente o coração de uma tempestade supercelular carregada de raios e saraiva cósmica.', 87000, 0.32, 2.78, ARRAY['wind', 'spikes']::TEXT[]),
(88, 'Cortina Eletromagnética da Aurora', 'sky_realm', 'Dancem sobre as fitas luminescentes da aurora polar que pintam a escuridão estratosférica.', 88000, 0.34, 2.79, ARRAY['moving', 'fragile']::TEXT[]),
(89, 'Corredor das Correntes de Jato', 'sky_realm', '🏃‍♂️ PERCURSO HORIZONTAL! Voe pelas correntes de jato da estratosfera a velocidades supersônicas!', 89000, 0.36, 2.81, ARRAY['wind', 'moving']::TEXT[]),
(90, '👑 CHEFÃO 18: Fênix das Tempestades', 'sky_realm', 'TEMPESTADE ZÊNITE AOS 90.000m! Domine a senhora alada dos ciclones árticos!', 90000, 0.26, 2.82, ARRAY['moving', 'fragile', 'wind', 'spikes']::TEXT[]),
(91, 'Pirâmides Esculpidas dos Andes', 'continents', 'As montanhas sagradas da cordilheira andina guardam segredos astronômicos milenares.', 91000, 0.28, 2.83, ARRAY['moving', 'wind']::TEXT[]),
(92, 'Fiordes Glaciais da Escandinávia', 'continents', 'O reino dos vikings e das geleiras azuis esculpidas pela passagem do tempo.', 92000, 0.3, 2.85, ARRAY['fragile', 'springs']::TEXT[]),
(93, 'Cânions Vermelhos de Uluru', 'continents', 'O coração sagrado do outback australiano pulsando sob a luz dourada do poente.', 93000, 0.32, 2.86, ARRAY['spikes', 'moving']::TEXT[]),
(94, 'Passarela da Grande Muralha Milenar', 'continents', '🏃‍♂️ PERCURSO HORIZONTAL! Salte entre as guaritas imperiais e torres de sinalização de fumaça!', 94000, 0.34, 2.87, ARRAY['moving', 'fragile']::TEXT[]),
(95, '👑 CHEFÃO 19: Esfinge Imperial Global', 'continents', 'O JULGAMENTO DAS CIVILIZAÇÕES AOS 95.000m! Desvende os mistérios da guardiã planetária!', 95000, 0.36, 2.88, ARRAY['moving', 'fragile', 'spikes', 'springs']::TEXT[]),
(96, 'Horizonte de Eventos Quântico', 'futuristic', 'A borda da realidade cósmica aos 96.000m onde a luz dobra em círculos perfeitos.', 96000, 0.26, 2.9, ARRAY['conveyor']::TEXT[]),
(97, 'Fenda Taquiônica dos 100k', 'futuristic', 'O tempo começa a se desfragmentar à medida que a altitude dos 100.000m se aproxima.', 97000, 0.28, 2.91, ARRAY['moving', 'fragile']::TEXT[]),
(98, 'Rede Neural das Constelações', 'futuristic', 'Conecte estrelas vivas através de saltos audaciosos acima de todas as galáxias conhecidas.', 98000, 0.3, 2.92, ARRAY['fragile', 'springs']::TEXT[]),
(99, 'Túnel do Hiperespaço Interestelar', 'futuristic', '🏃‍♂️ PERCURSO HORIZONTAL! Voe através do túnel de minhoca galáctico com reflexos relâmpago!', 99000, 0.32, 2.94, ARRAY['conveyor', 'moving', 'fragile']::TEXT[]),
(100, '👑 CHEFÃO 20: Chronos, O Senhor das Eras', 'futuristic', 'O MARCO DO CENTENÁRIO AOS 100.000m! O governante supremo das dimensões aguarda seu salto final!', 100000, 0.34, 2.95, ARRAY['moving', 'fragile', 'spikes', 'conveyor']::TEXT[]),
(101, 'Entrada do Vértice Abissal', 'ocean', 'Mergulhe no abismo oceânico cósmico invertido onde a escuridão é rompida por neon natural.', 101000, 0.36, 2.96, ARRAY['moving']::TEXT[]),
(102, 'Fontes Hidrotérmicas Negras', 'ocean', 'Chaminés vulcânicas expelindo minerais aquecidos a 400°C sob a pressão das profundezas.', 102000, 0.26, 2.98, ARRAY['springs', 'spikes']::TEXT[]),
(103, 'Cemitério de Submarinos de Titânio', 'ocean', 'Escale pelas carcaças de expedições pretéritas que sucumbiram à pressão esmagadora.', 103000, 0.28, 2.99, ARRAY['fragile', 'moving']::TEXT[]),
(104, 'Trincheira das Correntes de Fundo', 'ocean', '🏃‍♂️ PERCURSO HORIZONTAL! Deslize horizontalmente pelo leito submarino esquivando de algas vivas!', 104000, 0.3, 3, ARRAY['moving', 'conveyor']::TEXT[]),
(105, '👑 CHEFÃO 21: Kraken Abissal de Neon', 'ocean', 'PESADELO DAS FOSSAS AOS 105.000m! Enfrente o monstro cefalópode de tentáculos bioluminescentes!', 105000, 0.32, 3.01, ARRAY['moving', 'fragile', 'spikes']::TEXT[]),
(106, 'Dunas de Quartzo Prismático', 'crystal', 'O deserto cósmico onde cada grão de areia é um diamante bruto brilhando sob sóis gêmeos.', 106000, 0.34, 3.03, ARRAY['moving']::TEXT[]),
(107, 'Caverna dos Geodos Gigantes', 'crystal', 'Penetre no ventre da terra cósmica forrado de estalagmites ametistas brilhantes.', 107000, 0.36, 3.04, ARRAY['spikes', 'fragile']::TEXT[]),
(108, 'Obeliscos Refletores de Fótons', 'crystal', 'Espelhos monumentais alinhados para canalizar a energia da estrela central do mundo.', 108000, 0.26, 3.05, ARRAY['conveyor', 'moving']::TEXT[]),
(109, 'Passo do Vale dos Espelhos', 'crystal', '🏃‍♂️ PERCURSO HORIZONTAL! Atravesse a passarela de vidro cristalino cintilante em velocidade pura!', 109000, 0.28, 3.07, ARRAY['fragile', 'moving']::TEXT[]),
(110, '👑 CHEFÃO 22: Escorpião de Cristal Solar', 'crystal', 'DUELO NO SOL DO MEIO-DIA AOS 110.000m! O predador de carapaça adamantina ataca!', 110000, 0.3, 3.08, ARRAY['moving', 'fragile', 'spikes', 'conveyor']::TEXT[]),
(111, 'Câmara de Vácuo Magnético', 'quantum', 'O anel principal do acelerador onde prótons giram 11.000 vezes por segundo.', 111000, 0.32, 3.09, ARRAY['moving']::TEXT[]),
(112, 'Colisor de Quarks e Léptons', 'quantum', 'Colida com precisão milimétrica para aproveitar a energia liberada na fissão quântica.', 112000, 0.34, 3.11, ARRAY['springs', 'fragile']::TEXT[]),
(113, 'Trilhas de Íons Pesados', 'quantum', 'Feixes de partículas pesadas de chumbo aceleradas em direção ao ponto de impacto.', 113000, 0.36, 3.12, ARRAY['conveyor', 'spikes']::TEXT[]),
(114, 'O Anel Circular de Partículas', 'quantum', '🏃‍♂️ PERCURSO HORIZONTAL! Acelere até 99% da velocidade da luz pelo túnel magnético!', 114000, 0.26, 3.13, ARRAY['conveyor', 'moving']::TEXT[]),
(115, '👑 CHEFÃO 23: Bóson Descontrolado', 'quantum', 'SINGULARIDADE SUBATÔMICA AOS 115.000m! Impeça a criação de um micro buraco negro!', 115000, 0.28, 3.14, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(116, 'Encosta dos Fósseis Glaciais', 'dinosaur', 'Suba a montanha dos dinossauros onde o frio preservou esqueletos inteiros de milhões de anos.', 116000, 0.3, 3.16, ARRAY['wind', 'moving']::TEXT[]),
(117, 'Ninhos Suspensos nas Escarpas', 'dinosaur', 'Escale pelas fendas íngremes onde as mães pterodáctilos criam seus filhotes alados.', 117000, 0.32, 3.17, ARRAY['springs', 'fragile']::TEXT[]),
(118, 'Desfiladeiro dos Picos de Gelo', 'dinosaur', 'O vento corta como navalha enquanto pedras pontiagudas ameaçam perfurar sua subida.', 118000, 0.34, 3.18, ARRAY['spikes', 'wind']::TEXT[]),
(119, 'Planalto do Voo das Bestas Aladas', 'dinosaur', '🏃‍♂️ PERCURSO HORIZONTAL! Salte entre as correntes térmicas dos picos nevados pré-históricos!', 119000, 0.36, 3.2, ARRAY['moving', 'wind']::TEXT[]),
(120, '👑 CHEFÃO 24: Quetzalcoatlus Supremo', 'dinosaur', 'O SENHOR DOS CÉUS MESOZÓICOS AOS 120.000m! Conquiste o ápice do ninho jurássico!', 120000, 0.26, 3.21, ARRAY['moving', 'fragile', 'wind', 'spikes']::TEXT[]),
(121, 'Estação Abandonada de Tombstone', 'wild_west', 'O sino da estação soa na névoa do deserto anunciando a passagem do comboio amaldiçoado.', 121000, 0.28, 3.22, ARRAY['fragile', 'moving']::TEXT[]),
(122, 'Corte da Serra de Fogo', 'wild_west', 'Túneis escavados na rocha viva onde chamas dançam pelas frestas dos dormentes.', 122000, 0.3, 3.24, ARRAY['spikes', 'conveyor']::TEXT[]),
(123, 'O Expresso do Purgatório em Disparada', 'wild_west', '🏃‍♂️ PERCURSO HORIZONTAL! Corra sobre o teto metálico dos vagões em chamas do expresso fantasma!', 123000, 0.32, 3.25, ARRAY['conveyor', 'fragile', 'moving']::TEXT[]),
(124, 'Ponte Pênsil da Ravina Negra', 'wild_west', 'A travessia mais perigosa de todo o oeste: 800 metros de vão sobre o abismo insondável.', 124000, 0.34, 3.26, ARRAY['fragile', 'springs']::TEXT[]),
(125, '👑 CHEFÃO 25: Locomotiva Blindada Fantasma', 'wild_west', 'O APITO FINAL AOS 125.000m! Pare a locomotiva demoníaca antes que ela destrua a linha cósmica!', 125000, 0.36, 3.27, ARRAY['moving', 'fragile', 'spikes', 'conveyor']::TEXT[]),
(126, 'Domo dos Aros Holográficos', 'sports', 'A arena futurista onde atletas competem sem peso em meio a estrelas cintilantes.', 126000, 0.26, 3.29, ARRAY['springs']::TEXT[]),
(127, 'Pistas Cruzadas de Propulsão', 'sports', 'Corredores iluminados por LEDs que cruzam a arena em malhas geométricas velozes.', 127000, 0.28, 3.3, ARRAY['conveyor', 'moving']::TEXT[]),
(128, 'Barreiras Eletrizadas de Salto', 'sports', 'Salte sobre as traves de energia sem encostar nas pontas de descarga iônica.', 128000, 0.3, 3.31, ARRAY['spikes', 'fragile']::TEXT[]),
(129, 'Reta Final da Maratona Galáctica', 'sports', '🏃‍♂️ PERCURSO HORIZONTAL! Corra a grande maratona espacial rumo à fita de chegada estelar!', 129000, 0.32, 3.33, ARRAY['conveyor', 'springs', 'moving']::TEXT[]),
(130, '👑 CHEFÃO 26: Campeão da Gravidade Zero', 'sports', 'FINAL DO TORNEIO CÓSMICO AOS 130.000m! Destrone a lenda invicta dos esportes interplanetários!', 130000, 0.34, 3.34, ARRAY['moving', 'fragile', 'springs', 'conveyor']::TEXT[]),
(131, 'Geleia de Morango Saltitante', 'gastronomy', 'Um mundo feito inteiramente de confeitos mágicos onde cada salto é uma explosão doce.', 131000, 0.36, 3.35, ARRAY['springs']::TEXT[]),
(132, 'Cascatas de Chocolate Amargo', 'gastronomy', 'Rios espessos de cacau a 70% fluindo entre montanhas de suspiro e chantilly.', 132000, 0.26, 3.37, ARRAY['moving', 'fragile']::TEXT[]),
(133, 'Floresta dos Pirulitos de Vidro', 'gastronomy', 'Árvores de pirulito transparente com espinhos de caramelo quebradiço e cortante.', 133000, 0.28, 3.38, ARRAY['spikes', 'conveyor']::TEXT[]),
(134, 'Passarela dos Biscoitos Crocantes', 'gastronomy', '🏃‍♂️ PERCURSO HORIZONTAL! Atravesse a bancada das confeitarias cósmicas sem cair no leite quente!', 134000, 0.3, 3.39, ARRAY['fragile', 'moving']::TEXT[]),
(135, '👑 CHEFÃO 27: Gólem de Caramelo Ardente', 'gastronomy', 'SOBREMESA FINAL AOS 135.000m! Derrote o titã doce de caramelo antes que ele endureça seu caminho!', 135000, 0.32, 3.4, ARRAY['moving', 'fragile', 'spikes', 'conveyor']::TEXT[]),
(136, 'Dendritos de Prata Estelar', 'health', 'Salte pelas ramificações do córtex cósmico onde pensamentos universais se formam.', 136000, 0.34, 3.42, ARRAY['springs']::TEXT[]),
(137, 'Labirinto da Memória Quântica', 'health', 'Recordações de estrelas extintas flutuando em meio a correntes bioelétricas suaves.', 137000, 0.36, 3.43, ARRAY['fragile', 'moving']::TEXT[]),
(138, 'Nódulo de Conexão Axônica', 'health', 'O ponto de confluência onde bilhões de impulsos nervosos do universo colidem.', 138000, 0.26, 3.44, ARRAY['spikes', 'conveyor']::TEXT[]),
(139, 'Via Expressa dos Impulsos Cerebrais', 'health', '🏃‍♂️ PERCURSO HORIZONTAL! Percorra o tronco neural em alta velocidade desviando de sobrecargas elétricas!', 139000, 0.28, 3.46, ARRAY['conveyor', 'moving']::TEXT[]),
(140, '👑 CHEFÃO 28: Sinapse Hiperativa Omega', 'health', 'DESPERTAR DA MENTE AOS 140.000m! Prove a pureza da sua intenção diante da consciência viva do cosmos!', 140000, 0.3, 3.47, ARRAY['moving', 'fragile', 'spikes', 'springs']::TEXT[]),
(141, 'Terraços Flutuantes da Mesopotâmia', 'continents', 'Tijolos cozidos no sol da Babilônia sustentando árvores que tocam as estrelas.', 141000, 0.32, 3.48, ARRAY['conveyor', 'moving']::TEXT[]),
(142, 'Colunatas dos Templos Faraônicos', 'continents', 'O legado de Karnak e Luxor erguido aos 142.000m como testamento da ambição humana.', 142000, 0.34, 3.5, ARRAY['moving', 'fragile']::TEXT[]),
(143, 'Calçada Monumental dos Faraós e Reis', 'continents', '🏃‍♂️ PERCURSO HORIZONTAL! Corra pela avenida sagrada dos impérios do passado até o portão das eras!', 143000, 0.36, 3.51, ARRAY['moving', 'fragile', 'springs']::TEXT[]),
(144, 'Bastilhas dos Cumes da Antiguidade', 'continents', 'As torres de vigia finais que guardavam o portal para a última dimensão do cosmos.', 144000, 0.26, 3.52, ARRAY['wind', 'spikes']::TEXT[]),
(145, '👑 CHEFÃO 29: Colosso das Sete Civilizações', 'continents', 'A PROVA DA HISTÓRIA AOS 145.000m! Supere a fusão dos maiores guerreiros que o mundo já viu!', 145000, 0.28, 3.53, ARRAY['moving', 'fragile', 'spikes', 'conveyor', 'springs']::TEXT[]),
(146, 'Limiar do Vácuo Absoluto', 'futuristic', 'Você cruzou a fronteira do conhecido: o espaço agora é ouro líquido e silêncio absoluto.', 146000, 0.3, 3.55, ARRAY['springs', 'moving']::TEXT[]),
(147, 'Espiral das Constelações Vivas', 'futuristic', 'Cada plataforma é uma supernova em gestação sustentando seu avanço final.', 147000, 0.32, 3.56, ARRAY['moving', 'fragile']::TEXT[]),
(148, 'Fronteira Dimensional do Hiperespaço', 'futuristic', 'O universo está colapsando em pura beleza luminescente aos 148.000m de altitude.', 148000, 0.34, 3.57, ARRAY['conveyor', 'wind', 'spikes']::TEXT[]),
(149, 'O Corredor da Eternidade Cósmica', 'futuristic', '🏃‍♂️ PERCURSO HORIZONTAL! Corra pelo tapete dourado das galáxias rumo ao confronto derradeiro!', 149000, 0.36, 3.59, ARRAY['moving', 'conveyor', 'fragile', 'springs']::TEXT[]),
(150, '👑 CHEFÃO 30: O Demiurgo Eterno do Cosmos', 'futuristic', 'O CLÍMAX ABSOLUTO AOS 150.000m! Conquiste o trono eterno e torne-se a Lenda Imortal do JumpBall!', 150000, 0.26, 3.6, ARRAY['moving', 'fragile', 'spikes', 'conveyor', 'springs']::TEXT[])
ON CONFLICT (stage_number) DO UPDATE SET
  title = EXCLUDED.title,
  theme = EXCLUDED.theme,
  description = EXCLUDED.description,
  target_height = EXCLUDED.target_height,
  gravity = EXCLUDED.gravity,
  speed_factor = EXCLUDED.speed_factor,
  obstacle_types = EXCLUDED.obstacle_types;
